### ISSUE TITLE
SSL-Verschlüsselung ist wertlos

### ISSUE THREAD

**Issue by tmaier** [AGVM/www.agv-muenchen.de#216]
https://www.ssllabs.com/ssltest/analyze.html?d=agv%2dmuenchen.de

* schlüssellänge: nur 1024 bit
  https://bugzilla.mozilla.org/show_bug.cgi?id=881553
* unterstützt nicht TLS 1.2
* unterstützt nicht Forward Secrecy 

"Schuld": 1&1

//cc @agv-gs (zur Info an Philister-XX)

**Comment by michaellohr** [comment]
https://www.ssllabs.com/ssltest/analyze.html?d=agv-muenchen.de
https://shaaaaaaaaaaaaa.com/check/agv-muenchen.de

Dank Cloudflare hat sich das erledigt:
- Verwendet nun SHA-2
- Unterstützt Forward Secrecy
- Unterstützt TLS 1.2
- Schlüssellänge: lang genug
