### ISSUE TITLE
[Big Band] Big Band-Seite auf Homepage

### ISSUE THREAD

**Issue by Bewilderbeast** [AGVM/www.agv-muenchen.de#244]
Hallo,
wir hätten gerne auf der Big Band Seite folgende Änderungen:

* [ ] Vor dem Video noch eine Galerie / Lightbox wenn möglich? Mit diesen Bildern https://www.dropbox.com/sh/p51zc82qy90y4t1/AADpj1DVAbAGg45JU0m5YIgEa?dl=0

* [x] Wir hätten gerne eine Unterseite Termine, von der Art her wie das Große Orchester, mit folgenden Einträgen:

Proben:           Sonntags, 19-22 Uhr, Scholastika, Großer Saal (3. Stock)
Konzerte:        Samstag, 13.12.2014, 20:00, Scholastika, Großer Saal (3. Stock)
                       AGV Big Band plays Count Basie
                       Samstag, 21.02.2015, 20:00, Scholastika, Großer Saal (3.Stock)
                       Jazznight Jubiläumskonzert: 5 Jahre AGV Big Band

**Comment by AGropp** [comment]
Wie sieht es mit der Galerie aus, Max?

**Comment by mwel** [comment]
![14ws_bigband_header_whitelogo_01](https://cloud.githubusercontent.com/assets/5920017/6202835/8e0ec7e6-b500-11e4-89f6-0032e24b6912.jpg)

**Comment by mwel** [comment]
Natürlich ist jede andere Auflösung auch möglich, aber das ist die, die wir bisher auch haben.

**Comment by AGropp** [comment]
Erstellst Du bitte die Galerie?

**Comment by AGropp** [comment]
gehe ich recht der Annahme, dass Du das nicht hochgeladen hast, Max? Ich habe den Header bisher nicht gesehen...

**Comment by AGropp** [comment]
Maxi, wie schautsn endlich mit dem Header aus? Diese Karteileichen könnten mal entsorgt werden...

**Comment by michaellohr** [comment]
- Header zur 'Header-slideshow' hinzugefügt
- Gallerie mit den gegebenen Bildern vor dem Video eingefügt
