### ISSUE TITLE
Winterkonzert großes Orchester

### ISSUE THREAD

**Issue by HornAndreas** [AGVM/www.agv-muenchen.de#249]
Bitte Veranstaltungslink http://www.agv-muenchen.de/event/konzert-grosses-orchester/ beibehalten, da der QR-Code der Plakate darauf verweist.

Nachfolgend Inhaltliches. Format bleibt Euch überlassen, ich denke ihr setzt das wieder schön einheitlich zu den anderen Veranstaltungen um:

Programm:
Das Große Orchester des AGV präsentiert:

- F. Schubert Sinfonie Nr. 2, B-Dur, D 125

-W. A. Mozart Bastien und Bastienne
 Sopran: Maria Czeiler
 Tenor: Stephan Lin

Leitung: Michael Käsbauer

Konzerttext:
Im kommenden Winterkonzert greifen wir vom großen AGV-Orchester erstmals den Bereich der Oper bzw. des Singspiels mit auf. Es wird in der zweiten Konzerthälfte Wolfgang Amadeus Mozarts Singspiel "Bastien und Bastienne", KV5o konzertant zu hören sein. Die Solisten Maria Czeiler und Stephan Lin lassen uns dabei an ihrer kleinen Beziehungskrise teilhaben. Eine Geschichte nicht nur für Kinder.

In der ersten Hälfte ist u.a. die Symphonie Nr. 2 B-Dur, D 125 von Franz Schubert zu hören.

Eintritt frei-Spenden erbeten!

Plakat:
![bildschirmfoto 2015-01-19 um 10 32 43](https://cloud.githubusercontent.com/assets/9318268/5798386/d41c11f2-9fc6-11e4-8170-90f8d4b6f53e.png)

**Comment by AGropp** [comment]
Erledigt.
