### ISSUE TITLE
Ball der Musen, Buchungslinks löschen

### ISSUE THREAD

**Issue by agv-gs** [AGVM/www.agv-muenchen.de#250]
Bitte alle Links für die Ballbestellung auf der Homepage rausnehmen (auch den an die Geschäftsstelle).
Ballkarten sind nur noch an der Abendkasse, ab 19.00 Uhr erhältlich.

https://www.agv-muenchen.de/event/ball-der-musen-2015/?instance_id=1359

Den Rest bitte drin lassen, damit man noch die allgemeinen Infos zum Ball hat!
Danke

**Comment by AGropp** [comment]
Erledigt.
