### ISSUE TITLE
Musengruppenabend

### ISSUE THREAD

**Issue by Schlux** [AGVM/www.agv-muenchen.de#252]
Hallo Tobi,

kannst Du bitte drei Termine einstellen, die ich noch nicht im online-Semesterprogramm finde:

- Musengruppenleiter-Sitzung für Musengruppenleiter und -Sprecher: Dienstag, 24.02.2015, 18:00 Uhr, Silentium
- Semestergespräch jeder Musengruppe: Dienstag, 24.02.2015, 19:00 Uhr
- Musengruppenabend für alle Musengruppen-Mitglieder: Dienstag, 24.02.2015, 20:00 Uhr, Max-Planck-Saal und Philisterzimmer, Einladung zu Essen und Trinken

Wenn Du noch Text-Futter brauchst, benutze bitte das oder Auszüge daraus:

Liebe Mitglieder und Leiter der Musengruppen,

das Wintersemester 2014-2015 ist zu Ende gegangen und viele musische Veranstaltungen der vergangenen sechs Monate liegen hinter uns. Mit der Aufführung des Großen Orchesters in der Sendlinger Himmelfahrtskirche und dem Jubiläumskonzert der Big Band zum Fünfjährigen erwarten uns noch zwei echte Schmankerl! Sobald auch diese wunderbar verklungen sind, schließt sich fast nahtlos das große Beisammensein aller Musengruppen an: Als Anerkennung für Eurer großartiges Engagement in den jeweiligen Ensembles des AGVs möchte ich Euch hiermit im Namen der beiden Vorstandschaften recht herzlich einladen zum traditionellen Musengruppenabend am Dienstag, dem 24.02.2015 im AGV. Die Musengruppenleiter und -Sprecher bitte ich bereits um 18:00 Uhr zur Musengruppenleiter-Sitzung ins Silentium. Um 19:00 Uhr hat jede Musengruppe die Gelegenheit, zum Semestergespräch unter sich zu sein, bevor um 20:00 Uhr zu Essen und Trinken (?????) im Max-Planck-Saal und im Philisterzimmer geladen ist.

Ich freue mich auf Euer zahlreiches Erscheinen!
Stephan Müßig
Musenwart

**Comment by AGropp** [comment]
Erledigt. Ich hoffe, Schlux, zu Deiner Zufriedenheit.

**Comment by Schlux** [comment]
Hey Alex, ich wusste ja gar nicht, dass Du's bist! Danke für die schnelle Einpflegung! Deine Texte sind phänomenal kreativ. Das ist für mich immer gar nicht so leicht, um die einzelnen Termine einen erklärenden Text zu schreiben.
Ich hätte leider trotzdem bitte noch Korrekturwünsche. Geht das noch? Müsstest bitte nur jeweils die SOLL-Version rüberkopieren und online stellen. Danke Dir!


Musengruppenleiter-Sitzung
Feb 24 @ 18:00 – 19:00
IST:
Im Rahmen des Musengruppenabends lädt unser Musenwart, Stephan Müßig, zu einer gemeinsamen Sitzung der Musengruppenleiter ein. Thema ist vor allem der Rückblick auf das gesamte musische Geschehen des vergangenen Wintersemesters.

SOLL:
Im Vorfeld des Musengruppenabends bittet der Musenwart zu einer gemeinsamen Sitzung der Musengruppenleiter und der Musengruppensprecher. Themen sind u.a. Protokollkontrolle, Aufgabenlisten, Erwähnenswertes des vergangenen Wintersemesters und vor allem die zukünftige Konzertplanung.

Semestergespräch jeder Musengruppe
Feb 24 @ 19:00 – 20:00
IST
Ebenfalls als Teil des Musengruppenabends lädt Musenwart Stephan Müßig zum gemeinsamen Gespräch mit jeder Musengruppe ein. Dazu sind sowohl Musengruppenleiter als auch die Musengruppensprecher eingeladen.

SOLL
Als Teil des Musengruppenabends hat jede Musengruppe in Klausur die Möglichkeit, wenn gewünscht das vergangene Semester Revue passieren zu lassen, Zukünftiges zu besprechen oder zu proben. Die Musengruppenleiter und -sprecher begeben sich dazu wieder zu ihrer Gruppe.


Musengruppenabend
Feb 24 @ 20:00 – 23:00
IST 
Traditionell lädt der Musenwart Stephan Müßig alle Mitwirkenden unserer im AGV ansässigen Musengruppen zum Musengruppenabend ein. Dieses Ereignis dient dem gemeinsamen Dialog, dem Knüpfen neuer Freundschaften und gilt vorwiegend der Freude über das großartigen Schaffen und dem musischem Wirken der Musengruppen – und damit jedes einzelnen Mitgliedes – ebendem, was unseren Verein zu dem macht was es ist: einem Ort der Gemeinschaft und der Kultur.
Daher kommt zahlreich und bringt Hunger und Durst mit.
Anbei eine persönliche Einladung des Musenwartes.
Liebe Mitglieder und Leiter der Musengruppen,
das Wintersemester 2014-2015 ist zu Ende gegangen und viele musische Veranstaltungen der vergangenen sechs Monate liegen hinter uns. Mit der Aufführung des Großen Orchesters in der Sendlinger Himmelfahrtskirche und dem Jubiläumskonzert der Big Band zum Fünfjährigen erwarten uns noch zwei echte Schmankerl! Sobald auch diese wunderbar verklungen sind, schließt sich fast nahtlos das große Beisammensein aller Musengruppen an: Als Anerkennung für Eurer großartiges Engagement in den jeweiligen Ensembles des AGVs möchte ich Euch hiermit im Namen der beiden Vorstandschaften recht herzlich einladen zum traditionellen Musengruppenabend am Dienstag, dem 24.02.2015 im AGV. Die Musengruppenleiter und -Sprecher bitte ich bereits um 18:00 Uhr zur Musengruppenleiter-Sitzung ins Silentium. Um 19:00 Uhr hat jede Musengruppe die Gelegenheit, zum Semestergespräch unter sich zu sein, bevor um 20:00 Uhr zu Essen und Trinken (?????) im Max-Planck-Saal und im Philisterzimmer geladen ist.
Ich freue mich auf Euer zahlreiches Erscheinen!
Stephan Müßig
Musenwart

SOLL
Traditionell lädt das Philisterium alle Mitwirkenden unserer im AGV ansässigen Musengruppen zum Musengruppenabend ein. Dieses Ereignis dient dem gemeinsamen Dialog, dem Knüpfen neuer Freundschaften und gilt vorwiegend der Freude über das großartigen Schaffen und dem musischem Wirken der Musengruppen – und damit jedes einzelnen Mitgliedes – ebendem, was unseren Verein zu dem macht was es ist: einem Ort der Gemeinschaft und der Kultur.

Daher kommt zahlreich und bringt Hunger und Durst mit.

ENDE 
Danke!

**Comment by AGropp** [comment]
Habe die Änderungen eingefügt.

**Comment by Schlux** [comment]
Danke vielmals! Bis bald.
Schlux.

Ach ja: sag schon mal im Jungen Chor Bescheid. Nicht, dass sich wieder
keiner eingeladen fühlte ...

Stephan Müßig
____________________________
Heßstr. 59
80798 München
0160 - 7 343 719
stephan.muessig@web.de
Am 04.02.2015 16:55 schrieb "Alexander Gropp" <notifications@github.com>:
