### ISSUE TITLE
Aktualisierungen Junges Theater

### ISSUE THREAD

**Issue by markuswaidner** [AGVM/www.agv-muenchen.de#253]
Hallo :)
Musik&Theater-->Junges Theater-->Projekte, Termine
das hätte ich gerne aktualisiert.
Alt:
"Im Wintersemester 2014/2015 spielen wir “Die Zeit mit Simon” – ein Stück das unser Bundesbruder Daniel Rothenbücher geschrieben hat. Regie führt unser Mitglied Ricarda Schier. Die Aufführungen sind am 7., 8. und 9. November.

Wenn du Lust hast mitzuspielen sind die Imrpoabende ein idealer Einstieg."

Neu:
"Im Sommersemester 2015 spielen wir "Der Besuch der alten Dame" von Friedrich Dürrenmatt, Regie führt unser Bundesbruder Daniel Rothenbücher. Die Aufführungen sind am 8., 9. und 10 Mai."

**Comment by AGropp** [comment]
Erledigt.
