### ISSUE TITLE
Bitte alte SemesterHighlights löschen

### ISSUE THREAD

**Issue by agv-gs** [AGVM/www.agv-muenchen.de#254]
Bitte Termine bei Semesterhighlights löschen: Rektorenkneipe und Ball

https://www.agv-muenchen.de/veranstaltungen/

Danke M. Kunisch

**Comment by tmaier** [comment]
Die richtigen semesterhighlights des Semesters sind im Wiki

**Comment by AGropp** [comment]
Da das Semesterprogramm noch nicht steht will ich zeitgleich mit dessen Veröffentlichung die Highlights gleich mit einem Termin verknüpfen. Daher ist das Issue bis dahin zurückgestellt.

**Comment by AGropp** [comment]
Ich schließe es doch derweilen.
