### ISSUE TITLE
Sinfonisches Blasorchester des AGV

### ISSUE THREAD

**Issue by thefele** [AGVM/www.agv-muenchen.de#258]
Bitte unter Musengruppen neue Kategorie aufmachen mit Sinfonisches Blasorchester mit zwei Feldern "Projekte und Termine" sowie "Kontakt".
Könntet ihr eine email einrichten blasorchester@agv-muenchen.de
Ansprechpartner ist Florian Mayer, an ihn bitte die Verlinkung dieser Mailadresse einrichten.
florian.mayer.siegsdorf@googlemail.com

Musengruppenbeschreibung:

Aus Spass wird Spass!
Zu den verschiedensten Anlässen formierten sich immer wieder neue Gruppierungen mit dem Drang, endlich konkret zu werden und als festes Ensemble zusammen spielen zu dürfen. Der Weg führte vorbei an bayerischer Traditionsmusik, parallel hierzu wurden Projektweise Stücke wie die Ouvertüre für Harmoniemusik (Mendelssohn) oder aber die Sätze 1, 2 und 5 aus der Sinfonie "Lord of the Rings" (Johan de Meij) erfolgreich zur Aufführung gebracht.

Hieran wollen wir weiter anknüpfen und freuen uns auf dein Mitwirken!
Für Fragen und weitere Infos wendet euch einfach an "Kontakt"

**Comment by AGropp** [comment]
Hey Tobi, kannst Du bitte die Mailadresse einrichten?

**Comment by AGropp** [comment]
Seite besteht nun.

**Comment by AGropp** [comment]
Tobi, wie ist der aktuelle Stand?

**Comment by tmaier** [comment]
E-Mail ist eingerichtet

**Comment by tmaier** [comment]
Link zur neuen Seite ist nie schlecht.
https://www.agv-muenchen.de/musik-und-theater/symphonisches-blasorchester/

@AGropp folgendes muss noch gemacht werden:

1. die Sidebar rechts, wie bei den anderen Seiten
2. Bei https://www.agv-muenchen.de/musik-und-theater/ fehlt ein Button zum neuen Blasorchester

**Comment by thefele** [comment]
versteht ihr was ich eigentlich damit bezwecken wollte? dass quasi der Blasorcherstinteressierte eine Mail an blasorchester@agv-muenchen schreibt und diese Mail dann wiederum eine weiterleitung an den Flo Mayer bekommt, sodass seine private Mailadresse nicht weiter im Netz steht sondern im Hintergrund verwendet wird, wenn ich auf Mail klicke kommt nach wie vor die Privatmail!

**Comment by tmaier** [comment]
Habe die E-Mail-Adresse auf der Seite aktualisiert. Die anderen Punkte sind noch offen!

**Comment by AGropp** [comment]
Soweit sollte alles erledigt sein.
