### ISSUE TITLE
Überschriften berichtigen

### ISSUE THREAD

**Issue by markuswaidner** [AGVM/www.agv-muenchen.de#259]
https://www.agv-muenchen.de/musik-und-theater/junges-theater/biographie/

Die Semesterangaben stimmen nicht mit den Flyerbildern überein

Bühne der Missbilligung war im SS11
Jerry ist tot im SS12
Der grüne Kakadu im SS13
Lieblingsmenschen im WS 13/14
Ein Sommernachtstraum im SS14

Bitte einfach die fett gedruckten Überschriften entsprechend anpassen, vielen Dank!

**Comment by AGropp** [comment]
Erledigt.
