### ISSUE TITLE
letztes Stück hinzufügen

### ISSUE THREAD

**Issue by markuswaidner** [AGVM/www.agv-muenchen.de#260]
https://www.agv-muenchen.de/musik-und-theater/junges-theater/biographie/

bitte unser vergangenes Stück hinzufügen:

WS 14/15

**Flyerbild**

Daniel Rothenbücher: Die Zeit mit Simon (Regie Ricarda Schier)
![die_zeit_mit_simon_fb](https://cloud.githubusercontent.com/assets/8449802/6135042/a94a2c6a-b165-11e4-89e9-fddf53f45928.jpg)

**Comment by markuswaidner** [comment]
vielen Dank :)

**Comment by AGropp** [comment]
Erledigt. Darüber hinaus habe ich beim vergangenen Event auch den richtigen Flyer im korrekten Format eingefügt.
