### ISSUE TITLE
Änderungen in "Kontakt"

### ISSUE THREAD

**Issue by markuswaidner** [AGVM/www.agv-muenchen.de#261]
https://www.agv-muenchen.de/musik-und-theater/junges-theater/kontakt/

In der Bildbeschreibung:
alt: Verwirrt? Jack hilft gerne weiter. (Foto: Niklas Altekamp)
neu: Verwirrt? (Foto:Niklas Altekamp)

Im Text unter dem Bild "Jakob Zietsch" mit "Markus Waidner" ersetzen.

Vielen lieben Dank für diese und alle Änderungen!

**Comment by AGropp** [comment]
Erledigt.
