### ISSUE TITLE
Großes Theater - Aufführungen im März

### ISSUE THREAD

**Issue by philcap** [AGVM/www.agv-muenchen.de#263]
https://www.agv-muenchen.de/musik-und-theater/grosses-theater/projekte-termine/

Arsen und Spitzenhäubchen
von Joseph Kesselring

Die Villa der Brewster-Schwestern in Brooklyn ist eine Oase des friedlichen Glücks. Die Frau des Pfarrers, die örtliche Polizei – alle schätzen die außerordentliche Gastfreundschaft der bezaubernden älteren Damen Abby und Martha. Und dann sind da noch die zwei Brewster-Neffen: der irre Teddy, der sich für den amerikanischen Präsidenten hält, und Mortimer, ein Theaterkritiker.
Als dieser eines Abends kurz seine Tanten besucht, entdeckt er im Haus eine Leiche. Allerdings: Seinen Tanten kann das die Laune nicht verderben, ganz im Gegenteil! Was geht in der Villa vor sich? Was genau soll der „Panama-Kanal“, den Mortimers verrückter Bruder Teddy im Keller gräbt?
Und dann taucht auch noch der lange verschwundene dritte Bruder auf – ein gesuchter Verbrecher. Im Gepäck: noch ein Toter! Ein Haus, in das täglich Polizisten zum Tee kommen, mit nunmehr zwei Leichen! Mindestens...
Mit diesem Stück schrieb Joseph Kesselring 1941 eine der schwärzesten und skurrilsten Komödien der Weltliteratur.

Aufführungstermine:

13. / 14. / 15. März 2015 & 20. / 21. / 22. März 2015
jeweils 19:30
![flyer_arsen_2015_vorne](https://cloud.githubusercontent.com/assets/3063576/6204386/71f22866-b549-11e4-8fc2-b0b4214f82a3.jpg)

**Comment by philcap** [comment]
Bei den Terminen muss der erste 13. heißem....

**Comment by AGropp** [comment]
Erledigt.
