### ISSUE TITLE
Sinfonisches Blasorchester des AGV

### ISSUE THREAD

**Issue by thefele** [AGVM/www.agv-muenchen.de#264]
https://www.agv-muenchen.de/musik-und-theater/symphonisches-blasorchester/projekte-und-termine/

Erstes Treffen:
Mittwoch 22.4.2015 um 19:00 Uhr im 2. Stock Scholastika

Bläserworkshop/Probenwochenende: 5.-7.6.2015 in der Scholastika; Beginn Freitag 19:00 Uhr

Programm: u.a. First Suite, Alfred Reed

**Comment by AGropp** [comment]
Erledigt.
