### ISSUE TITLE
Link auf Mitgliederverwaltung ändern

### ISSUE THREAD

**Issue by ka026804** [AGVM/www.agv-muenchen.de#266]
Nachdem der SV beschlossen hat, unser Mitgliederverwaltungsprogramm nicht zu verwenden, sollte der Link auf das Mitgliederverzeichnis in unserer Homepage nicht meht auf die übergeordnete SV-Seite bei Laterne verweisen. Daher bitte den Link "Mitgliederverzeichnis" (Seite Interna) abändern in:
https://sv.laterne.de/login?mpn=Login&gruppe=M

Vielen Dank

Andreas Keil

**Comment by ka026804** [comment]
Könnte dieses Ticket bitte jemand aufgreifen?

**Comment by AGropp** [comment]
Erledigt.
