### ISSUE TITLE
Großes Orchester Updates

### ISSUE THREAD

**Issue by AndreasHornHorn** [AGVM/www.agv-muenchen.de#267]
Betrifft: https://www.agv-muenchen.de/musik-und-theater/grosses-orchester/projekte-termine-konzerte/

Jeweilige Kategorien ersetzen:

Probenbeginn: Di 14.04.2015, 19.30 Uhr
AGV, Großer Saal (3. Stock)

Reguläre Probe:  Bleibt gleich

Programm: 
- Arrangements Sinatra/Bublé u.a. (zusammen mit der BigBand)
- C. Frank d-moll Sinfonie 
- L. v. Beethoven: Tripelkonzert
- A. Khachaturian: Masquerade, 

Öffentliche Generalprobe: keine

Konzert: 
- Fr 10.07.2015, 19.30 Uhr  Stiftungsfestkonzert (Arrangements Sinatra/Bublé u.a.) - Himmelfahrtskirche Sendling
- Sa 31.10.2015, 19.30 Uhr Herbstkonzert (Franck, Beethoven, Khachaturian) - Aula der LMU

**Comment by tmaier** [comment]
@mbergmann1324: kannst du die genannten Konzerte auch auf Seite als Veranstaltungen anlegen und dann auch wieder auf der oben genannten Seite Verlinken?

**Comment by AGropp** [comment]
Nur zur Information: Wenn wir heute Abend beim Webmastertreffen das aktuelle Semesterprogramm auf der Website einpflegen, wird auch die Veranstaltung erstellt. Den Link werden wir hinzufügen.

**Comment by AGropp** [comment]
Servus Andi,

also ich habe den Link zum Stiftungsfestkonzert jetzt erstellt... Für das Herbstkonzert habe ich noch kein Event erstellt. Das ist dann fällig, wenn wir das Wintersemester-programm einpflegen im Sommer.

Daher ist dieses Issue nun erst mal erledigt.
