### ISSUE TITLE
Vorstandsämter aktualisieren

### ISSUE THREAD

**Issue by markuswaidner** [AGVM/www.agv-muenchen.de#268]
https://www.agv-muenchen.de/ueber-den-agv/vorstaende/aktivitas/

Bitte die Namen der Vorstandsämter und das Semester  aktualisieren : 

xx - Markus Waidner
xxxx - Clemens Liewald
FM - Robin Ruhnau

Danke

**Comment by AGropp** [comment]
Erledigt.
