### ISSUE TITLE
Foto Junger Chor

### ISSUE THREAD

**Issue by agv-gs** [AGVM/www.agv-muenchen.de#269]
Bitte das Foto des Jg. Chores auf der Homepage als jpg an die Geschäftsstellle senden.
Wir benötigen es für Werbemaßnahmen für das Jubiläumskonzert.
Sind noch Fotos von Konzertaufnahmen vorhanden?
Danke
M. Kunisch

**Comment by AGropp** [comment]
Erledigt.
