### ISSUE TITLE
Improtheaterwettstreit

### ISSUE THREAD

**Issue by markuswaidner** [AGVM/www.agv-muenchen.de#270]
![flyer_impromatchsose 2015](https://cloud.githubusercontent.com/assets/8449802/6601072/cb8a6618-c813-11e4-8b92-06e7a28511e6.jpg)

Bitte auf die Homepage + Veranstaltung im Kalender erstellen.

Und bitte noch folgenende Veranstaltungstext drunter:

Der Kampf zweier Teams um Ruhm und Ehre, und nicht zuletzt um Deine Gunst! Egal ob spannende Agentenaction oder emotionale Liebesszene... Wir spielen, was Du Dir wünschst! Alles frei improvisiert! Nach den Szenen entscheiden Du und der Rest des Publikums, welches der beiden Teams die Vorgaben am Besten umgesetzt hat. Es hängt also von Dir ab, welches Team als glorreicher Sieger, und welches als niedergeschlagener Verlierer von der Bühne geht. Freu Dich auf einen witzigen, unterhaltsamen und spannungsgeladenen Abend!

Unsere Gegenspieler sind diesmal eine Überaschung. Aber eines ist sicher: Mit Ihnen wird es ein genialer Abend werden :)

**Comment by AGropp** [comment]
Soweit erledigt. Sobald wir endlich wieder Facebook-Rechte haben wird das Event auch dort erstellt und entsprechend verlinkt.
