### ISSUE TITLE
Sinfonisches Blasorchester

### ISSUE THREAD

**Issue by jsteinert** [AGVM/www.agv-muenchen.de#273]
Bitte den Text unter folgendem Link ändern:

https://www.agv-muenchen.de/musik-und-theater/symphonisches-blasorchester/projekte-und-termine/

IST:

Freitag, 5. Juni 2015 – Sonntag, 6. Juni 2015, 19:30 Uhr, AGV, Großer Saal (3. Stock)

SOLL:

Freitag, 5. Juni 2015 – Sonntag, 7. Juni 2015, 19:30 Uhr, AGV, Großer Saal (3. Stock)

**Comment by AGropp** [comment]
Erledigt.
