### ISSUE TITLE
Hochladen des aktuellen Chorbriefes 

### ISSUE THREAD

**Issue by BirgitRitter** [AGVM/www.agv-muenchen.de#277]
Hallo,

kann an dem Link zu dem Probenplan der neue Plan hinterlegt werden?
Der neue Plan befindet sich hier: https://www.dropbox.com/home/AGV

Ich hoffe, es klappt mit dem Zugriff! 

vlg Birgit

**Comment by AGropp** [comment]
Sorry, Zugang geht nicht. Das ist lediglich die Anmeldepage. Bitte direkt hier einpflegen oder per Mail schicken.

**Comment by BirgitRitter** [comment]
Hi, an welche Email Adresse kann ich ihn den schicken? 

vlg Birgit

**Comment by AGropp** [comment]
Bitte schicke die Datei an: AlexanderGropp@t-online.de

**Comment by AGropp** [comment]
Erledigt.
