### ISSUE TITLE
[Impro] FB Veranstaltung - 20. Mai erstellen

### ISSUE THREAD

**Issue by Jazkiob** [AGVM/www.agv-muenchen.de#281]
Bitte erstellt die FB Veranstaltung und AGV Veranstaltung für unseren nächsten Improabend.

Wann: 20. Mai 2o15
Wo: AGV - Max Planck Saal
Wer: schlAGVertig

Text: 
Auch dieses Semester freuen wir uns, Euch einen schönen Impro-Abend bieten zu können. Um 19:30 heißt es wieder: 3 2 1 LOS!
Unser Improteam schlAGVertig gibt alles, um Euch mit kurzweiligem Schauspiel nach Euren Vorschlägen den Abend zu einem erinnerungswürdigen Event zu machen.

Der Eintritt ist wie immer frei -über Spenden würden wir uns freuen.

Wir freuen uns auf Euch :)
----------------

Bild: 
FB-Banner: https://www.dropbox.com/s/qz10rn1l4dke9sl/Poster_Theatersport%20SoSe%202014_RGB_FB_Banner_klein.jpg?dl=0

Für AGV-Website:
https://www.dropbox.com/s/chi0f3r2ocxbk8z/Poster_SoSe%202015_RGB_Website.jpg?dl=0

**Comment by AGropp** [comment]
Erledigt.
