### ISSUE TITLE
Bigband Jazznight

### ISSUE THREAD

**Issue by Aktivitas-x** [AGVM/www.agv-muenchen.de#283]
https://www.agv-muenchen.de/event/agv-big-band-jazz-night/
Bitte den Flyer als Bild einfügen und den Text als Beschreibung schalten. 
Außerdem eine Veranstaltung auf FB erstellen. 
Besten Dank!
Flyer: 
https://www.dropbox.com/sh/ynd7xj4jsx3b2e0/AACpbFfHixkQneOWGAcPRs8Ja?dl=0
Text: 
Der Sommer vergreift sich an München. Der Englische Garten wird von den Sonnenanbetern wiederbelebt und der Flaucher verwandelt sich in einen Partystrand mit Lagerfeuern. Wer sehnt sich da nicht nach Palmen, einem kühlen Cocktail und heißen Sambarhythmen?

Wir auch! Daher haben wir für die kommende Jazznight eine ganze Palette an südamerikanischen Rhythmen und sommerlichen Grooves einstudiert, mit denen wir euch in einen mitreißenden, percussiv beschwingenden und pulsierenden Sommerabend voll karibischer Lebensfreude entführen werden.

Besonders freuen wir uns auch wieder auf die Gesangsnummern, für die wir wie immer unsere bezaubernde Sängerin Sonja Lachenmayr featuren.

**Comment by tmaier** [comment]
Tipp: Wenn der Flyer eine PNG oder JPEG-Datei ist, dann musst du sie nicht in dropbox speichern, sondern kannst ihn hier beim Issue hoch laden. Siehe z.B. #282

**Comment by Bewilderbeast** [comment]
Könnt ihr bitte auch noch die Konzertseite der Big Band überarbeiten? 
https://www.agv-muenchen.de/musik-und-theater/big-band/projekte-termine-konzerte/

Da müsste hin:
Samstag, 06.06.2015, 20:00 Uhr
Jazz Night

Freitag, 10.07.2015, 19:00 Uhr
Stiftungsfestkonzert
Gemeinsames Konzert mit dem Großen Orchester des AGV

![2015_06_06 jazz night a6 1 0 0](https://cloud.githubusercontent.com/assets/9408724/7639819/0c7326fe-fa7f-11e4-89ba-2e0dfe2edb80.png)

**Comment by tmaier** [comment]
@Bewilderbeast Normalerweise sollte jeder einzelne Arbeitsauftrag ein Github Issue sein. Jetzt wird nämlich auch @Aktivitas-x mit E-Mails genervt, die nur deinen Auftrag betreffen.

@Bewilderbeast: Hast du auch den Text von der Rückseite?

**Comment by Bewilderbeast** [comment]
Der Text:
Der Sommer vergreift sich an München. Der Englische Garten wird von den Sonnenanbetern wiederbelebt und der Flaucher verwandelt sich in einen Partystrand mit Lagerfeuern. Wer sehnt sich da nicht nach Palmen, einem kühlen Cocktail und heißen Sambarhythmen? Wir auch! Daher haben wir für die kommende Jazz Night eine ganze Palette an südamerikanischen Rhythmen und sommerlichen Grooves einstudiert, mit denen wir euch in einen mitreißenden, percussiv beschwingenden und pulsierenden Sommerabend voll karibischer Lebensfreude entführen werden. Besonders freuen wir uns auch wieder auf die Gesangs-nummern, für die wir wie immer unsere bezauberndeSängerin Sonja Lachenmayr featuren. Der Eintritt ist wie immer frei!

Tobi hat das Issue statt mir erstellt, weil ich keinen Rechnerzugang hatte und es langsam knapp wird - deshalb hat sich das überschnitten

**Comment by mbergmann1324** [comment]
Habe das Event und die Bigband Seite aktualisiert.
