### ISSUE TITLE
Sinfonisches Blasorchester

### ISSUE THREAD

**Issue by thefele** [AGVM/www.agv-muenchen.de#287]
https://www.agv-muenchen.de/musik-und-theater/symphonisches-blasorchester/

ist das Foto halbwegs tauglich zumindest?! dass mal irgendwas im Netz ist...

![blasorchester](https://cloud.githubusercontent.com/assets/3012029/8171885/d07d6b72-13bb-11e5-8481-6a7b87368b66.jpg)

**Comment by AGropp** [comment]
Leider nicht tauglich. Die Qualität ist zu schlecht. Vielleicht gibt es Bilder vom Filmmusikkonzert die besser sind? Das könnte man dann auch in Facebook verwenden.

Ansonsten erledigt.
