### ISSUE TITLE
Sinfonisches Blasorchester

### ISSUE THREAD

**Issue by thefele** [AGVM/www.agv-muenchen.de#288]
https://www.agv-muenchen.de/musik-und-theater/symphonisches-blasorchester/projekte-und-termine/

folgende Änderungen:
Programm: Neujahrskonzert (Fledermausouvertüre, Can Can, u.v.m.)
Konzerte: Fr. 15.1. sowie Sa. 16.1.2016 um 19:30 Uhr, So. 17.1.2016 um 17:00 Uhr im Großen Saal
Probenbeginn WS 2015/16: Mittwoch 14.10.2015 19:30 Uhr
Regelmäßige Proben: Mittwoch 19:30-22:00 Uhr (2. Stock/Hölle) Scholastika in der Ledererstr. 5
Probenwochenenden: 13.-15.11.2015 sowie 8.-10.1.2016

**Comment by AGropp** [comment]
Erledigt.
