### ISSUE TITLE
Eintrag des BR Ferrnsehbeitrages in "AGV in der Presse"

### ISSUE THREAD

**Issue by Aktivitas-x** [AGVM/www.agv-muenchen.de#289]
Ort: https://www.agv-muenchen.de/medien/agv-in-der-presse/
Bitte fügt hier einen Link (am besten gleich mit Sreenshots, wenn die Links irgendwann nicht mehr funktionieren) mit Datum und einem kurzen Begleittext ähnlich denen in FB hinzu.
Verlinkung des Videos selbst: http://www.br.de/mediathek/video/musikalische-studentenverbindung-100.html
Link des Artikels: http://www.br.de/fernsehen/ard-alpha/sendungen/campusmagazin/studentenverbindung-agv-100.html
Verl
Link der "Herrenrunde": http://www.br.de/fernsehen/ard-alpha/sendungen/campusmagazin/gesangverein-web-only-100.html
Beispiel für einen Screenshot: ![screenshot](https://cloud.githubusercontent.com/assets/8321620/8327215/02e5a406-1a67-11e5-9031-07aec2875755.JPG)

**Comment by tmaier** [comment]
Macht außerdem einen Beitrag auf die Startseite. Der kann da auch ein paar Monate stehen.

**Comment by Aktivitas-x** [comment]
Info von Campus MAGAZIN: "In der Mediathek sind die Videos immer nur 7 Tage, aber auf unserer Homepage mit dem Artikel dazu ist es mindestens ein Jahr online, deswegen würde ich empfehlen den kompletten Artikel zu verlinken. LG"
In dem Artikel ist aber nur das Video der "Herrenrunde" verlinkt, nicht der ganze Beitrag. Diesen gibt es nur in der Mediatek (schon seit einem Monat, aber nun angeblich nur noch bis 3.7.
Also bitte jetzt auf die Startseite einen Link mit dem Beitrag (in der Mediathek) und dem Artikel, dann in einer Woche den Link mit dem Video überprüfen und gegebenenfalls diesen rauslöschen, den Link zum Artikel aber noch weiter auf der Startseite lassen.
In das Archiv nur den Link zum Artikel mit entsprechender Beschreibung und dem Screenshot von der Mediathek.

**Comment by Aktivitas-x** [comment]
irgendwie wurde das Video mit der Herrenrunde gelöscht. Der Link funktioniert nicht mehr, bitte nehmt ihn wieder raus. Sorry!

**Comment by AGropp** [comment]
Alles klar. Links sind entfernt.

**Comment by tmaier** [comment]
Bitte Video auch auf https://www.agv-muenchen.de/medien/mp3s-und-videos/ stellen

**Comment by tmaier** [comment]
Video ist außerdem auf Youtube!
https://www.youtube.com/watch?v=A1z9NauZnmE

**Comment by Aktivitas-x** [comment]
https://www.agv-muenchen.de/medien/agv-in-der-presse/

falscher Text: "Der BR hat uns in unserer Scholastika besucht. Das Reporterteam wollte wissen, was eine Studentenverbindung ausmacht und welche Prinzipien der AGV sich verpflichtet. Dabei räumten einige Bundesbrüder mit typischen Vorurteilen gegenüber Studentenverbindungen auf."

korrigierter Text: "Der BR hat uns in unserer Scholastika besucht. Das Reporterteam wollte wissen, was eine Studentenverbindung ausmacht und welchen Prinzipien der AGV sich verpflichtet. Dabei räumten einige Bundesbrüder mit typischen Vorurteilen gegenüber Studentenverbindungen auf.

**Comment by mbergmann1324** [comment]
Video bei den Medien und den neuen Text reingetan
