### ISSUE TITLE
[Improtheater

### ISSUE THREAD

**Issue by Jazkiob** [AGVM/www.agv-muenchen.de#290]
Wo: https://www.agv-muenchen.de/musik-und-theater/improvisationstheater/

Was: Ändern des Textes, des Bildes und der Bildunterschrift

# Neuer Text:

IST:
Die Wurzeln unserer Theatergruppe liegen in Impro-Abenden, über die wir 2010 zusammengefunden haben. Nach wie vor treffen wir uns jeden zweiten Sonntag Abend im AGV für gemeinsame Theaterspiele.

Bei Interesse, melde Dich doch einfach bei unserem Theatersprecher.

SOLL:
[Altes Bild so lassen]
Offenes Impro für Jedermann [Überschrift]
Improvisationsgeschick  ist eine Fähigkeit, die man oft im echten Leben benötigt. So ist es kein Wunder, dass alltägliche Themen wie magische Steine, genetisch veränderte Bienen, ein Pony, das zu einem Monster wird und viel mehr, bei unseren Impro-Abenden oft als Inspiration zum spielen verwendet wird.  

Hört sich nach Spaß an? Selber voller Ideen und Inspiration? {Melde dich einfach} <Bitte mit Verlinkung auf die Emailadresse impro@agv-muenchen.de> bei unserem Leiter. Wir freuen uns immer über neue Gesichter :)

[Neues Bild -> https://www.dropbox.com/s/1dzjxtpy85xdb0u/schlAGVertig_Logo_final.png?dl=0 ]

Unser Team für Auftritte - schlAGVertig [Überschrift]

Neben der, für jeden, offenen Improtheatergruppe, die jeden zweiten Sonntag im Monat probt, hat sich bei uns ein festes und eingespieltes Improteam gebildet. Unter dem Namen "schlAGVertig" bestreiten wir regelmäßig größere und kleinere Auftritte. Von Kindergeburtstagen über Straßenfestivals bis zu festen Bühnen mit mehreren hundert Zuschauern sind wir stets bereit zu spielen.

Interesse einmal eine Improgruppe auf die heimische Bühne zu holen? 
Kontaktieren Sie uns einfach unter impro@agv-muenchen.de.

Alle Infos zu unseren Auftritten finden sie über Event-Kalender oder auf unserer {Facebookseite} <Verlinkung auf https://www.facebook.com/schlagvertig >. 

# Neues Bild:
https://www.dropbox.com/s/1dzjxtpy85xdb0u/schlAGVertig_Logo_final.png?dl=0

# Neue Bildunterschrift:
Unser Heimteam schlAGVertig

**Comment by AGropp** [comment]
Servus Jack,

ich bin an der Sache dran. Nur leider spinnt unser Server mal wieder und ich kann gerade nichts uploaden. Ich versuche es heute noch einmal.

Liebe Grüße,
Alex

**Comment by Jazkiob** [comment]
Top, danke dir :)

2015-06-25 12:20 GMT+02:00 Alexander Gropp <notifications@github.com>:

**Comment by AGropp** [comment]
Erledigt.
