### ISSUE TITLE
Erstellen eines FB Events über GitHUB

### ISSUE THREAD

**Issue by BirgitRitter** [AGVM/www.agv-muenchen.de#291]
Hallo, bitte einen Event erstellen für das 154. Stiftungsfestkonzert

"Die Vorfreude steigt! Bald findet das 154. Stiftungsfestkonzert des AGV München statt!

Der große Chor des AGV wird zusammen mit den Solisten Sonja Lachenmayr und Maximilian Höcherl die Gospel Mass von Robert Ray aufführen. Die Big Band und das große Orchester werden die Zuhörer zusammen mit Solist Maximilian Höcherl Stücke von Frank Sinatra, Pat Pack u.a. präsentieren!

Leitung: Thomas Hefele und Franz Schledorn"

Datum / Zeit: 10.07.2015 / 19.30
Ort: HImmelfahrtskirche Sendling

Eintritt frei - Spenden erbeten!

**Comment by AGropp** [comment]
Alles erledigt.
