### ISSUE TITLE
Stiftungsfestkonzert, Beschreibung

### ISSUE THREAD

**Issue by Aktivitas-x** [AGVM/www.agv-muenchen.de#293]
Ich habe zum Stiftungsfestkonzert in der Beschreibung noch ein, zwei Sätze ergänzt (auf Facebook habe ich es gleich geändert, bitte nehmt es auch hier mit rein!).
Bitte ändert unter https://www.agv-muenchen.de/event/stiftungsfestkonzert-2/

alter Text: "In diesem Jahr swingt und groovt es beim 154. Stiftungsfestkonzert: Der große Chor wird die Gospel Mass von Robert Ray zum besten geben – unterstützt von den Solisten Sonja Lachenmayr und Maximilian Höcherl. Im zweiten Teil freuen wir uns auf Klassiker des Swings von Frank Sinatra, Pat Pack und vielen mehr – gespielt von der Big Band und dem großen Orchester. Den Gesang übernimmt auch hier Maximilian Höcherl."

neuer Text: "In diesem Jahr swingt und groovt es beim 154. Stiftungsfestkonzert: Der große Chor wird die Gospel Mass von Robert Ray zum besten geben - unterstützt von den Solisten Sonja Lachenmayr und Maximilian Höcherl.

Im zweiten Teil freuen wir uns auf Klassiker des Swings von Frank Sinatra, Pat Pack und vielen mehr - als Arrangements, wie sie von Michael Bubblé und Robbie Williams aufgenommen wurden: Feeling good, Cry me a River, Quando, Quando, Quando, Mr Bojangles, Beyond the sea,...
Bei uns spielt die Big Band gemeinsam mit dem großen Orchester. Den Gesang übernimmt Maximilian Höcherl."

den Rest (Eintritt frei, Leitung, etc.) genau so behalten

Besten Dank! Tobi

**Comment by Aktivitas-x** [comment]
Bitte bearbeitet diesen Issue endlich mal! Ich weiß, es ist Prüfungsphase, aber für mich auch!

**Comment by AGropp** [comment]
Tut mir Leid, ich habe das wohl übernommen. Danke für den Hinweis.
An alle anderen: Bitte auch mal wieder was tun!

Erledigt.
