### ISSUE TITLE
Neue Satzung

### ISSUE THREAD

**Issue by Aktivitas-x** [AGVM/www.agv-muenchen.de#294]
https://www.agv-muenchen.de/ueber-den-agv/interna/

Bitte hier die alte Satzung der Aktivitas ersetzen durch die Neue: "Aktuelle Satzung (Stand 2015)"

Hier der Link zum PDF:
https://drive.google.com/open?id=0BxXSDA9oVXbyVVBnWnkwUHRHVlU

Danke!

**Comment by AGropp** [comment]
Ersetzt.
