### ISSUE TITLE
[Impro] FB Veranstaltung - 03. August erstellen

### ISSUE THREAD

**Issue by Jazkiob** [AGVM/www.agv-muenchen.de#295]
Bitte erstelle die FB Verasntaltung mit folgenden Daten:

Wann: 03. August 2015 - ab 19:30 Uhr
Wo: AGV Zweiter Stock - Max Planck

Titel: Ab in den Urlaub - Improtheater mit schlAGVertig
Bild: https://www.dropbox.com/s/pix0uii0m0em1nb/FB_Veranstaltungbanner-01.png?dl=0

Bitte ladet direkt Leute an -> Das letzte Mal war die Veranstaltung mi 0 Gästen.

Text: Als letzte Veranstaltung im Sommersemester läutet unser Improteam schlAGVertig [VERLINKUNG, wenn möglich] mit dem Motto "Ab in den Urlaub" die Semesterferien ein.

Wie bei jedem Improabend entscheidet ihr, wo es an dem Abend überall hingeht, was wir auf der Bühne erleben und wem wir alles begegnen.

Der Eintritt ist wie immer frei - über Spenden würden wir uns freuen.

Wir freuen uns auf Euch :)

PS: Da es schon einige Nachfragen gab: Der Abend ist auch zum passiven zuschauen gedacht. Also keine Sorge, ihr müsst nicht auf die Bühne ;)

**Comment by tmaier** [comment]
https://www.facebook.com/events/882418161846991/
