### ISSUE TITLE
Erstellen eines FB Events über GitHUB

### ISSUE THREAD

**Issue by BirgitRitter** [AGVM/www.agv-muenchen.de#296]
Hallo, 

bitte erstellt ein Event mit dem Titel:

"Aufführung der Christnacht von Joseph Haas - Alpenländische Stücke zur Adventszeit für Chor, Orchester und Sprecher"

Ort: Himmelfahrtskirche Sendling
Datum: 11.12.2015
Uhrzeit: 19:30

Mehr Informationen habe ich noch nicht! VG Birgit

**Comment by BirgitRitter** [comment]
Hallo, hat das jemand gelesen?

**Comment by AGropp** [comment]
Servus Birgit,

wir erstellen das Event, sobald wir das gesamte neue Semesterprogramm einstellen.

**Comment by BirgitRitter** [comment]
Hey, ah ok alles klar! :)

**Comment by AGropp** [comment]
Hallo Birgit, sicher wirst Du gehört haben, dass wir technische Probleme haben und die Website neu aufgesetzt wird. Dies soll innerhalb der nächsten Woche passieren. Ich werde die Veranstaltung dort erstellen. Kannst Du Dich bis dahin schon einmal um einen Flyer kümmern? Gruß, Alex
