### ISSUE TITLE
betrifft: https://www.agv-muenchen.de/musik-und-theater/grosses-orchester/dirigent/

### ISSUE THREAD

**Issue by Mikel123** [AGVM/www.agv-muenchen.de#301]
vorher:
Michael Käsbauer 
altes Bild
Text: 
Der 28-Jährige schloss im Juni 2012 die Meisterklasse von Professor Michael Gläser im Fach Dirigieren/Chor an der Hochschule für Musik und Theater München ab. Davor studierte er – ebenfalls in München – Musik für Lehramt an Gymnasien. Ergänzend besucht der junge Dirigent internationale Kurse sowie stimmphysiologische und musikwissenschaftliche Vorträge und unterrichtete 2008 und 2009 in der Chorleiterausbildung des Bayerischen Sängerbundes. Bereits mit 17 Jahren war Käsbauer Organist in seiner Heimatpfarrei und sammelte dort als Leiter des Kirchenchors erste Erfahrungen am Dirigentenpult. Seit 2008 leitet er den Maria-Ward-Chor Nymphenburg, mit dem er chorsinfonische und A-cappella Werke aller Epochen aufführt. 2009 entstand auf seine Initiative das Vokalensemble „libera mente“, ein Projektchor, der sich auf anspruchsvolle Werke von Alter Musik bis hin zu zeitgenössischer Musik spezialisiert hat. Nicht zuletzt steht er seit 2010 an der Spitze des Großen Orchesters im Akademischen Gesangverein München. Hier dirigiert er sinfonische Werke von Haydn bis hin zu Mahler und Gershwin.
Homepage: www.michael-kaesbauer.de

nachher:
Michael Konstantin
altes Bild
Text:
Michael Konstantin besucht derzeit das Kapellmeisterstudium bei Professor Guido Johannes Rumstadt in Nürnberg. Er arbeitet immer wieder mit Ensembles wie dem Kammerorchester Mannheim, den Nürnberger Symphonikern, dem Georgischen Kammerorchester Ingolstadt u.a.. Als Studienleiter und Assistent begleitete er die Produktion "Der Mond" bei den Carl-Orff-Festspielen in Andechs 2015. Sein Operndebüt hatte er im Februar 2015 mit “La fedeltà premiata” von Joseph Haydn im Markgrafentheater Erlangen.
2012 schloss er die Meisterklasse von Professor Michael Gläser im Fach Chordirigieren an der Hochschule für Musik und Theater München ab. Dort studierte er ebenfalls Musik für Lehramt an Gymnasien.
Ergänzend besucht der junge Dirigent internationale Kurse (u.a. “International Masterclass Jorma Panula”) sowie stimmphysiologische und musikwissenschaftliche Vorträge und unterrichtete 2008 und 2009 in der Chorleiterausbildung des Bayerischen Sängerbundes. Bereits mit 17 Jahren war Michael Konstantin Organist in seiner Heimatpfarrei und sammelte dort als Leiter des Kirchenchors erste Erfahrungen am Dirigentenpult. Seit 2008 leitet er den Maria-Ward-Chor Nymphenburg, mit dem er chorsinfonische und A-Cappella-Werke aller Epochen aufführt. Nicht zuletzt steht er seit 2010 an der Spitze des Großen Orchesters im Akademischen Gesangverein München. Hier dirigiert er sinfonische Werke von Haydn bis hin zu Mahler und Gershwin.

 Homepage: www.michael-konstantin.de

**Comment by AGropp** [comment]
Servus Michael,

ich habe die Änderungen übernommen - allerdings fehlt mir noch ein Bild von Dir. Kannst Du mir das direkt an: AlexanderGropp@t-online.de schicken? Danke

**Comment by AGropp** [comment]
WTF? Mir wird gerade was klar.... sorry Michi xD Ich glaube wir müssen uns wirklich dringend mal wieder zusammensetzen
