### ISSUE TITLE
betrifft: https://www.agv-muenchen.de/musik-und-theater/grosses-orchester/biographie/

### ISSUE THREAD

**Issue by Mikel123** [AGVM/www.agv-muenchen.de#302]
bitte alle "Michael Käsbauer" in "Michael Konstantin" ändern
--> "Michael Konstantin" immer als Ganzes (als Marke) ... bitte eine Trennung in Vor- und Nachname vermeiden!
(habe den Namen auf dieser Seite 7mal gefunden)

**Comment by AGropp** [comment]
Erledigt.
