### ISSUE TITLE
Emailverteiler vorstandschaft@agvm-aktivitas.de

### ISSUE THREAD

**Issue by Aktivitas-x** [AGVM/www.agv-muenchen.de#305]
Bitte den Verteiler vorstandschaft@agvm-aktivitas.de so ändern, dass alle Vorstände die Mails bekommen, also:

x@agvm-aktivitas.de
xx@agvm-aktivitas.de
xxx@agvm-aktivitas.de
xxxx@agvm-aktivitas.de
gw@agvm-aktivitas.de
bw@agvm-aktivitas.de
fm@agvm-aktivitas.de

vielen Dank!

Grüße, Markus

**Comment by tmaier** [comment]
Erledigt.

![untitled copy](https://cloud.githubusercontent.com/assets/350038/9616634/958eccb4-50ff-11e5-8397-e381b30cfb12.jpg)
