### ISSUE TITLE
Bitte Veranstaltung erstellen

### ISSUE THREAD

**Issue by Aktivitas-x** [AGVM/www.agv-muenchen.de#306]
Servus,

bitte erstellt die Veranstaltung zur Aufführung vom Jungen Theater. Bitte auch eine Facebookveranstaltung mit dem Text von der Flyerrückseite. Vielen lieben Dank!
Alle Informationen finden sich auf dem Flyer :)

![flyer_final-page-001](https://cloud.githubusercontent.com/assets/8321620/9773901/896475fa-5745-11e5-9f65-f131c1964828.jpg)
![flyer_final-page-002](https://cloud.githubusercontent.com/assets/8321620/9773902/896d9356-5745-11e5-8d71-96548ba79962.jpg)

**Comment by Aktivitas-x** [comment]
habe gerade die FB-Veranstaltung erstellt, bitte noch die Veranstaltung auf der HP erstellen.

habe das schonmal gemacht weil wir gerne mit der Werbung beginnen wollen.

Grüße

Markus

**Comment by AGropp** [comment]
Erledigt.
