### ISSUE TITLE
Großer Chor Falscher 1. Probentermin

### ISSUE THREAD

**Issue by thefele** [AGVM/www.agv-muenchen.de#307]
https://www.agv-muenchen.de/musik-und-theater/grosser-chor/projekte-termine-konzerte/

1. Probe nicht am 13.10. sondern bereits am 6.10.

Bitte Konzert ergänzen
Weihnachtskonzert: 11.12.2015 um 19:30 Uhr

**Comment by thefele** [comment]
nach wie vor nicht geändert!
Bitte ändert das...sonst steh ich in der ersten Probe ohne Leute da...arg
Danke

**Comment by AGropp** [comment]
erledigt.
