### ISSUE TITLE
neues Chorfoto

### ISSUE THREAD

**Issue by thefele** [AGVM/www.agv-muenchen.de#308]
https://www.agv-muenchen.de/musik-und-theater/grosser-chor/
Bild bitte durch folgendes ersetzen...
![img_0377](https://cloud.githubusercontent.com/assets/3012029/9775084/daedf156-574c-11e5-8449-78ea05d8a528.JPG)

**Comment by AGropp** [comment]
Es tut mir Leid Tom, aber wir können derzeit keine neuen Bilder hochladen - der Upload macht Probleme. Tobi und ich sind allerdings dran die Seite komplett neu aufzusetzen und dann natürlich das neue Bild zu benutzen.

**Comment by AGropp** [comment]
Habe das jetzt nochmal versucht... Leider funktionieren nach wie vor keine Uploads. Ich bin da wirklich mit meinem Latein am Ende.

**Comment by thefele** [comment]
hier die gleiche geschichte wie mit dem Blasorchesterfoto! Das alte ist einigermaßen fürchterlich!wär super wenn man das ersetzen könnte! Danke

**Comment by mbergmann1324** [comment]
Es hat geklappptttttttt!!!!!!
