### ISSUE TITLE
falscher 1. Probentermin / Konzertzeiten Sinfonisches Blasorchester

### ISSUE THREAD

**Issue by thefele** [AGVM/www.agv-muenchen.de#309]
https://www.agv-muenchen.de/musik-und-theater/symphonisches-blasorchester/projekte-und-termine/

1. Probe: Mittwoch 7.10.2015 um 19:30

Neujahrskonzert:
Fr. 15.1. um 20:00 Uhr
Sa. 16.1. um 19:00 Uhr
So. 17.1. um 17:00 Uhr

Ergänzung zu den Probenwochenenden:
27.-29.11.2015

**Comment by mbergmann1324** [comment]
Ich habe jetzt bei den Probenwochenden, das Wochenende vom Januar drin gelassen.
