### ISSUE TITLE
Sinfonisches Blasorchester Kontaktmail Weiterleitung einrichten

### ISSUE THREAD

**Issue by thefele** [AGVM/www.agv-muenchen.de#311]
Servus,
bis jetzt ist die Blasorchestermail nur an Flo Mayer verlinkt...könnte man das bitte auch für die Miriam Festl machen?
miriam.festl@googlemail.com

**Comment by mbergmann1324** [comment]
Hat sie einen besonderen Titel wie Orchestersprecherin oder sowas

**Comment by AGropp** [comment]
Erledigt?

**Comment by tmaier** [comment]
Haben jetzt ein eigenes Konto. @thefele hat die Zugangsdaten und hoffentlich verteilt.
