### ISSUE TITLE
[Impro] FB Veranstaltung - 05. Oktober erstellen

### ISSUE THREAD

**Issue by Jazkiob** [AGVM/www.agv-muenchen.de#312]
Bitte erstelle die FB Verasntaltung mit folgenden Daten @mbergmann1324 

Wann: 05. Oktober 2015 - ab 19:30 Uhr
Wo: AGV Zweiter Stock - Max Planck

Titel: Improtheater mit schlAGVertig
Bild: https://www.dropbox.com/s/pix0uii0m0em1nb/FB_Veranstaltungbanner-01.png?dl=0

Bitte ladet direkt Leute an -> Das letzte Mal war die Veranstaltung mi 0 Gästen...
Und bitte beachtet, die VERLINKUNG im Text zu machen und alles in Klammern rauszulöschen

Text: Hallo Improbegeisterte! Am 3.10. geht, zumindest bei uns, das Semester los mit unserem ersten Impro-Abend. Wie immer sind wir von schlAGVertig [VERLINKUNG EINFÜGEN ZU FB SEITE SCHLAGVERTIG] genauso gespannt wie ihr, was wohl passieren wird. Wird ein wütender Killer durch die Räume des AGV schleichen oder findet ein alter Mann durch Zufall seine Jugendliebe wieder? 
Ihr entscheidet mit Euren Vorschlägen, was wir spielen :)
Kommt vorbei und seid dabei wenn es wieder heißt:
3, 2, 1 - LOS!!!!!

Der Eintritt ist wie immer frei - über Spenden würden wir uns freuen.

Wir freuen uns auf Euch :)

PS: Da es schon einige Nachfragen gab: Der Abend ist auch zum passiven zuschauen gedacht. Also keine Sorge, ihr müsst nicht auf die Bühne ;)

**Comment by AGropp** [comment]
Soweit erledigt. Sollte wider Erwarten das Calender-Plugin auf der Website funktionieren, werde ich den entsprechenden Link zur Website setzen.
