### ISSUE TITLE
Veranstaltung anpassen

### ISSUE THREAD

**Issue by Aktivitas-x** [AGVM/www.agv-muenchen.de#313]
Servus,

wir sind leider vertraglich verpdlichtet noch folgendes auf die HP zu setzen. und zwar hier:
https://www.agv-muenchen.de/event/jg-theater-krankheit-der-jugend/

Am besten ganz unten unter "Krankheit der Jugend auf FB" schreiben:

"Krankheit der Jugend von Ferdinand Bruckner können Sie auch als eBook lesen. Alle Shops, die den Titel vorrätig haben, finden Sie unter: www.textbuehne.eu"

Vielen Dank. Das kann vielleicht auch in kleinerer Schriftart da stehen, aber wir müssens wie gesagt leider wegen dem Vertrag mit dem Verlag hinschreiben.

Grüße

Markus

**Comment by AGropp** [comment]
Erledigt.
