### ISSUE TITLE
Junges Orchester 

### ISSUE THREAD

**Issue by Mariabeier** [AGVM/www.agv-muenchen.de#314]
https://www.agv-muenchen.de/musik-und-theater/junges-orchester/kontakt/

Bitte anstatt:

Unser Orchestersprecher-Team

Maria Beier, Johann Steinert und Tobias Boolakee

folgendes übernehmen:

Unser Orchestersprecher-Team

Maria Beier, Julia Wimmer, Johann Steinert und Tobias Boolakee

Vielen Dank und Grüße Maria Beier

**Comment by AGropp** [comment]
Erledigt.
