### ISSUE TITLE
https://www.agv-muenchen.de/musik-und-theater/grosses-orchester/projekte-termine-konzerte/

### ISSUE THREAD

**Issue by Mikel123** [AGVM/www.agv-muenchen.de#315]
Alte Fassung:
Terminplan

PROBENBEGINN
Dienstag, 14.4.2015, 19:30AGV, Großer Saal (3. Stock)
REGULÄRE PROBEN
Dienstags, 19:30 Uhr, AGV, Großer Saal (3. Stock)
PROGRAMM
Arrangements Sinatra/Bublé u.a. (zsm. mit der Big Band)
C. Franck d-moll Sinfonie
L.v. Beethoven: Tripelkonzert
A. Khachaturian: Masquerade
ÖFFENTLICHE GENERALPROBE
keine
KONZERT
Freitag, 10.07.2015, 19:30 Uhr, Stiftungsfestkonzert (Arrangements Sinatra/Bublé u.a.) -Himmelfahrtskirche Sendling
Samstag 31.10.2015, 19:30 Herbstkonzert (Franck, Beethoven, Khachaturian) – Aula der LMU

NEUE FASSUNG:
Terminplan

PROBENBEGINN
Dienstag 03. November 2015
REGULÄRE PROBEN
Dienstags, 19:30 Uhr, AGV, Großer Saal (3. Stock)
PROGRAMM
C. Franck d-moll Sinfonie
L.v. Beethoven: Tripelkonzert
A. Khachaturian: Masquerade

ab 03.11.2015:
Klavierkonzert KV 482 von W.A. Mozart
(Solist: Tung-Hsing Tsai)
Marimbaphonkonzert von Séjourné
(Solistin: Vivi Vassileva)
Filmmusik

ÖFFENTLICHE GENERALPROBE
keine
KONZERT
Samstag 31.10.2015, 19:30 Herbstkonzert (Franck, Beethoven, Khachaturian) – Aula der LMU
(--> bitte mit Link zum Veranstaltungskalender)
Sonntag 07.02.2015, !7:00 Soiree - Großer Saal der Scholastika (AGV)

(BILD kommt per Mail an Alex Gropp)

**Comment by mbergmann1324** [comment]
Bild ist noch nicht drin und der Link zum Veranstaltungskalender klappt nur der Kalender eben nicht.
Sonst fertig
