### ISSUE TITLE
Impromatch Veranstaltung FB

### ISSUE THREAD

**Issue by Improtheater** [AGVM/www.agv-muenchen.de#316]
Hallo, bitte die beiden Veranstaltungen in FB erstelllen :) @mbergmann1324

1. Termin: Freitag, 23.10.2015, ab 19:00 Uhr
Wo: AGV, großer Saal
Titel: Impromatch mit ImproMacchiato
Bild: 
![schlagvertig logo fb auftritte](https://cloud.githubusercontent.com/assets/15000733/10316301/ed090ade-6c5e-11e5-9c6d-a4f830a34e50.jpg)

Text: Unser erstes von zwei Impromatches dieses Semester wird ein unvergesslicher Abend für allle beteiligten werden. Unsere Gäste kommen heute aus Fürstenfeldbruck, nämlich das Team Impro Macchato! Wie immer sind wir von schlAGVertig [VERLINKUNG EINFÜGEN ZU FB SEITE SCHLAGVERTIG] genauso gespannt wie ihr, was wohl passieren wird. Wird ein wütender Killer durch die Räume des AGV schleichen oder findet ein alter Mann durch Zufall seine Jugendliebe wieder?
Ihr entscheidet mit Euren Vorschlägen, was wir spielen und mit Eurem Appplaus, welches Team am Ende den Tagessieg nach Hause nehmen wird :)
Kommt vorbei und seid dabei wenn es heißt:
3, 2, 1 - LOS!!!!!

Der Eintritt ist wie immer frei - über Spenden würden wir uns freuen.

Wir freuen uns auf Euch :)

PS: Da es schon einige Nachfragen gab: Der Abend ist auch zum passiven zuschauen gedacht. Also keine Sorge, ihr müsst nicht auf die Bühne ;)

2. Termin: Samstag, 24.10.2015, ab 19:00 Uhr
Wo: AGV, großer Saal
Titel: Impromatch mit den Caipiranhas
Bild: 
![schlagvertig logo fb auftritte](https://cloud.githubusercontent.com/assets/15000733/10316301/ed090ade-6c5e-11e5-9c6d-a4f830a34e50.jpg)

Text: Unser zweites Impromatch dieses Semester werden wir mit den Caipiranhas aus München spielen! Mal sehen wie sich das Team schlAGVertig [VERLINKUNG EINFÜGEN ZU FB SEITE SCHLAGVERTIG] heute schlagen wird. Kommt es zum spannenden Duell? Sehenn wir eine romantische Szene, vielleich sogar zwischen beiden Teams? Wir wissen es nicht, aber ihr entscheidet es mit Euren Vorschlägen!
Kommt vorbei und seid dabei wenn es heißt:
3, 2, 1 - LOS!!!!!

Der Eintritt ist wie immer frei - über Spenden würden wir uns freuen.

Wir freuen uns auf Euch :)

PS: Da es schon einige Nachfragen gab: Der Abend ist auch zum passiven zuschauen gedacht. Also keine Sorge, ihr müsst nicht auf die Bühne ;)

Text Ende

Bitte direkt Leute einladen, damit möglichst viele frühzeitig das Event sehen und wir die Hütte voll kriegen :)
Danke schonmal.

**Comment by Jazkiob** [comment]
Servus Jungs,

Hab den Flyer zum Event erstellt. Vielleicht könnt ihr das auch direkt für FB nutzen:

PDF Version:
https://www.dropbox.com/s/akldk55yirg84ir/Flyer_ImpromatchWiSe%202015.jpg?dl=0

JPG:
https://www.dropbox.com/s/akldk55yirg84ir/Flyer_ImpromatchWiSe%202015.jpg?dl=0

Beste Grüße

Jack

PS: Da die Verlinkungen leider nicht funktionieren, lassen wir sie diesmal einfach raus ;)
Und bitte macht sowohl mich (Jack) als auch Henrik (Improschauspieler) zum Admin.

@AGropp , du kennst das Prozedere ja bereits. Danke nochmal, dass es das letzte Mal so gut und schnell geklappt hat ;)

**Comment by AGropp** [comment]
Hey Jack,

ich sitze gerade dran, wie soll denn der Text sein?

Gruß, Alex

**Comment by Jazkiob** [comment]
Den Text hat Henrik oben in den Issue geschrieben :)

**Comment by AGropp** [comment]
Erledigt. Sobald Henrik meine Freundschaftsanfrage bestätigt, kann ich ihn auch als weiteren Gastgeber hinzufügen.
