### ISSUE TITLE
Programm und Projekte Junges Orchester

### ISSUE THREAD

**Issue by jsteinert** [AGVM/www.agv-muenchen.de#318]
https://www.agv-muenchen.de/musik-und-theater/junges-orchester/projekte-termine-konzerte/

Folgendes ersetzen:

Terminplan Sommersemester 2015
Programm
	Ouvertüre aus Freischütz; Weber
Viola Konzert; Hoffmeister
Symphonie fantastique; Berlioz
Konzerte
	Samstag, 17.10.2015 um 19:30 Uhr Himmelfahrtskirche (Kidlerstraße)
Probenbeginn
	Sektprobe – Kennenlernprobe am Donnerstag 12.2.2015 um 19:30
Reguläre Proben
	ab 5.3.2015 immer Donnerstag, 19:30 Uhr. AGV – Großer Saal (3. Stock)
Probenwochenende
	Probenwochenenden: 24.4.-26.4. im AGV unter Anleitung professioneller Dozenten; 12.6.-14.6. Musikakademie Marktoberdorf; 25.9.-27.9. im AGV

Durch:
Terminplan Wintersemester 2015/16
Programm
	Joseph Haas - Christnacht (mit Großem Chor des AGV)
        Walzerprogramm (u.a. Radetzky-Marsch, Tritsch-Tratsch Polka)
Konzerte
	Freitag, 11.12.2015 um 19.30 Uhr in der Himmelfahrtskirche Sendling - Christnacht
        Freitag, 15.01.2016 um 20.00 Uhr im AGV - Neujahrskonzert mit Walzerprogramm
        Samstag, 16.01.2016 um 19.00 Uhr im AGV - Neujahrskonzert mit Walzerprogramm
        Sonntag, 17.01.2016 um 17.00 Uhr im AGV - Neujahrskonzert mit Walzerprogramm
Probenbeginn
	22.10.2015 um 19:30
Reguläre Proben
	ab 22.10.2015 immer Donnerstag, 19:30 Uhr. AGV – Großer Saal (3. Stock)
Probenwochenende
	20.11. - 22.11. im AGV 
        08.01. - 10.01. im AGV

**Comment by jsteinert** [comment]
Ich will keinen Stress machen, aber das neue Semester hat schon angefangen und potentielle Aspiranten finden keine Infos zum aktuellen Programm etc. Wäre klasse wenn das diese Woche noch erledigt werden könnte :)

**Comment by tmaier** [comment]
@mbergmann1324
