### ISSUE TITLE
Test von info@agv-muenchen.de

### ISSUE THREAD

**Issue by Aktivitas-x** [AGVM/www.agv-muenchen.de#319]
Wir sind uns nicht sicher, ob Mails, die an info@agv-muenchen.de geschickt werden, bei uns ankommen. Die Mail steht auf den Faltblättern, es ist also wichtig, dass die Mails ankommen. 

Könnt ihr nachsehen, wo die Mails hingehen? Wenn nicht an fm oder mich oder andere Vorstände, dann bitte stellt es so ein, dass die Mails an vorstandschaft@agvm-aktivitas.de gehen.

vielen Dank! Beste Grüße

Markus

**Comment by tmaier** [comment]
Wird wohl jetzt an den XX weiter geleitet.
