### ISSUE TITLE
Umstellung der Umleitung von jungestheater@agv-muenchen.de

### ISSUE THREAD

**Issue by Aktivitas-x** [AGVM/www.agv-muenchen.de#320]
vielleicht habt ihr mitbekommen, dass Jannick jetzt meinen Posten als Theatersprecher übernimmt. Ich bitte euch deshalb die Umleitung der an die Mail jungestheater@agv-muenchen.de geschickten Mails auf Jannicks Mailadresse weiterleiten zu lassen. Jannicks Mail ist:

jannick.pfort@gmx.de

Vielen lieben Dank,

Markus

**Comment by tmaier** [comment]
Weiterleitung entfernt; eigenes Postfach eingerichtet.
