### ISSUE TITLE
FB Evennt Improtheater

### ISSUE THREAD

**Issue by Improtheater** [AGVM/www.agv-muenchen.de#321]
Bitte folgendes Event in FB erstellen und Leute einladen:

Was:  Improtheaterabend mit schlAGVertig
Wann: Montag, 2.10.2015
Wo: Ledererstr. 5, 2. Stock, Max-Planck-Saal
Bild: 
![schlagvertig logo fb auftritte](https://cloud.githubusercontent.com/assets/15000733/10734028/8a02828c-7c01-11e5-81ba-9db142ce5d4d.jpg)

Text:
Hallo Improbegeisterte!

Am 2.11. laden wir Euch ein zu unserem zweiten Impro-Abend in diesem Semester. Wie immer sind wir von schlAGVertig genauso gespannt wie ihr, was wohl passieren wird. Gibt es Pinguine zu sehen? Was macht einen Western erst richtig spannend? Welches Geheimnis sollen wir für Euch lüften?
Ihr entscheidet mit Euren Vorschlägen, was wir spielen :)
Kommt vorbei und seid dabei wenn es wieder heißt:
3, 2, 1 - LOS!!!!!

Der Eintritt ist wie immer frei - über Spenden würden wir uns freuen. :)

PS: Da es schon einige Nachfragen gab: Der Abend ist auch zum passiven zuschauen gedacht. Also keine Sorge, ihr müsst nicht auf die Bühne ;)

**Comment by Improtheater** [comment]
Sorry, Datum natürlich 2.11.2015

**Comment by AGropp** [comment]
Erledigt.
