### ISSUE TITLE
Hochladen des Flyers auf der Homepage

### ISSUE THREAD

**Issue by BirgitRitter** [AGVM/www.agv-muenchen.de#322]
Hallo,

wäre es möglich hier
https://www.agv-muenchen.de/musik-und-theater/grosser-chor/projekte-termine-konzerte/
ein PDF zu hinterlegen?

An welche Emailadresse kann ich das schicken, ich kann PDF hier nicht hochladen.

vg Birgit

**Comment by AGropp** [comment]
schicke es bitte an meine Privatadresse: AlexanderGropp@t-online.de

**Comment by tmaier** [comment]
Mittlerweile soll man auch PDF Dateien hochladen können.

http://zmwangx.github.io/img/20150719-github-attachment-new-formats.png

**Comment by AGropp** [comment]
Erledigt. Werbung werde ich sogleich auch auf Facebook erstellen - das ist zur Zeit unsere effektivste Plattform, da die neue Website sich noch im Aufbau befindet.
