### ISSUE TITLE
Mail weiterleiten

### ISSUE THREAD

**Issue by Aktivitas-x** [AGVM/www.agv-muenchen.de#323]
Der Ballotagewart bekommmt leider die Mails die an bw@agv-muenchen.de gehen nicht. Das sind wohl immer noch einige.

Bitte also eine Weiterleitung von bw@agv-muenchen.de zu bw@agvm-aktivitas.de einrichten.

Vielen lieben Dank

Hung & Markus

**Comment by tmaier** [comment]
Hi Hung,

Bitte füge die andere Adresse zu dem Google Account hinzu. Siehe z.B. http://praxistipps.chip.de/e-mail-aliase-in-gmail-erstellen-so-gehts_13588

**Comment by tmaier** [comment]
Gibts hier ein Update? Kann man das schließen?

**Comment by Aktivitas-x** [comment]
ich frage mal bei Hung nach

**Comment by Aktivitas-x** [comment]
er ist noch nicht dazu gekommen, das zu machen. Bitte also noch nicht schließen. Danke der Nachfrage!

**Comment by AGropp** [comment]
Any News?

**Comment by Aktivitas-x** [comment]
Also geht wohl nicht. Hung hat da schon mit Tpbi gesprochen. 
Können wir den alten Account zurücksetzen um ein neues Passwort zu bekommen?

**Comment by AGropp** [comment]
In diesem Fall muss ich das dann wohl wieder an @tmaier weitergeben. Sorry.

**Comment by tmaier** [comment]
@michidk kannst du hier helfen?

**Comment by michaellohr** [comment]
Nur damit ich das jetzt richtig verstanden habe:
bw@agv-muenchen.de leitet zu tanzkurs@agv-muenchen.de weiter, und von diesem Account soll ein neues Passwort vergeben werden? (Das Passwort dann Hung Nguyen zuschicken)

**Comment by blacktalon567** [comment]
Also es ist so, dass ich momentan nur Zugang zu bw@agvm-aktivitas.de habe.

Ich hatte versucht, die bw@agv-muenchen.de Adresse zu der aktuellen hinzuzufügen, wie Tobi es oben beschrieben hat, das hat aber nicht geklappt (ich weiß auch nicht, wie das überhaupt klappen soll ohne irgendwelche Zugangsdaten der alten Adresse. Sonst kann man ja jede beliebige Adresse hinzufügen). 

Ich denke, das sinnvollste ist, dass das pw von bw@agv-muenchen.de resettet wird und ich dann das neue pw bekomme, um damit arbeiten zu können. Dann kann ich auch eine Weiterleitung selbst einrichten.

**Comment by michaellohr** [comment]
bw@agv-muenchen.de ist eigentlich nur eine Weiterleitung zu tanzkurs@agv-muenchen.de welches ein eigenes Postfach ist. Wer hat den Zugang zu tanzkus@agv-muechen.de? Ich blick hier noch nicht ganz durch.

bw@agv-muenchen.de leitet jetzt erstmal nach tanzkurs@agv-muenchen.de und bw@agvm-aktivitas.de weiter.

**Comment by blacktalon567** [comment]
Alles klar, das erfüllt für mich den Zweck.
Hab's getestet und es funktioniert.

Danke!
