### ISSUE TITLE
Veranstaltungen Big Band

### ISSUE THREAD

**Issue by Bewilderbeast** [AGVM/www.agv-muenchen.de#325]
Hallo,
könnt Ihr bitte die Seiten der Big Band anpassen?

https://www.agv-muenchen.de/musik-und-theater/big-band/

Neuer Text:
Wir proben immer sonntags von 19 – 22 Uhr.

Dieses Semester spielen wir zwei Konzerte:
Das erste Konzert findet am 12.12.2015 um 20:00 Uhr im großen Saal der Scholastika statt. Kurz vor Weihnachten zünden wir für Sie noch einmal ein musikalisches Feuerwerk, das Sie sich auf keinen Fall entgehen lassen sollten. Zusammen mit unserem Leiter Franz Schledorn haben wir wieder ein Repertoire aus neuen Nummern und den beliebtesten Stücken der letzten Spielzeit zusammengestellt.

Mit dabei sind unter an­de­rem das fett geswungene Groovin` Hard von Don Menza, diverse Funk Nummern und nicht zuletzt moderne Arrangements von dem Münchner Komponisten Wolfgang Roth.Als Special Guest begrü˚en wir dieses Mal die Sängerin Elis Roseira, die Ihnen die Leichtigkeit des brasilianischen Bossa Nova näherbringt!

Das zweite Konzert ist wie jedes Semester unsere Jazz Night am 27.02.2016 um 20 Uhr ebenfalls im großen Saal der Scholastika.

Und
https://www.agv-muenchen.de/musik-und-theater/big-band/projekte-termine-konzerte/

Unter Konzerte:
Samstag, 12.12.2015, 20:00 Uhr
Weihnachtskonzert
Samstag, 27.02.2016, 20:00 Uhr
Jazz Night

Vielen Dank!

**Comment by mbergmann1324** [comment]
Done, auf der Bigband seite habe ich den Link zum Konzert vom 9.02 gelassen.
