### ISSUE TITLE
Verbesserung Homepage

### ISSUE THREAD

**Issue by JannickP** [AGVM/www.agv-muenchen.de#327]
Geht ganz schnell:

Auf https://www.agv-muenchen.de/musik-und-theater/junges-theater/kontakt/
Statt: "Sprecher Jannick Pfortr"
Bitte: "Sprecher Jannick Pfort"
Da ist ein "r" zuviel ;)

**Comment by tmaier** [comment]
Hi Jannick,

Du hast leider noch nicht alle Möglichkeiten in Betracht bezogen um das Problem zu lösen.

Ich schlage eine öffentlich-rechtliche Namensänderung vor. Siehe hierzu http://www.muenchen.de/rathaus/Stadtverwaltung/Kreisverwaltungsreferat/Standesamt-und-Urkunden/Namensaenderungen/-ffentlich-rechtliche-Namensaenderung.html

Bitte teile mir mit wann du damit fertig bist, damit wir dieses Issue schließen können.

VG

Tobias

**Comment by JannickP** [comment]
Hey Tobi,

Leider leben meine Großeltern noch und bestehen auf Enkelkinder mit dem Namen "Pfort". Ich denke solange sie noch nicht den Geist aufgegeben haben, würde ich ihnen gerne (zumindest) die Hoffnung erhalten und daher meinen Namen erstmal behalten ;)

Deshalb würde ich gerne nach einer anderen Lösung suchen.
Falls dir was einfallen sollte, gib bitte Bescheid.

VG
Jannick PFORT

**Comment by mbergmann1324** [comment]
Immer meckern. Ich änder es gleich sorry
Am 21.11.2015 11:39 schrieb "JannickP" <notifications@github.com>:
