### ISSUE TITLE
Mailadresse erstellem

### ISSUE THREAD

**Issue by Aktivitas-x** [AGVM/www.agv-muenchen.de#329]
Servus zusammen,

zunehmend sind bei großen Konzerten die Platzkontingente in unserer Scholastika zu klein bzw. dann zu klein, wenn man sie nicht plant. In der Vergangenheit wurde das bereits schonmal vom Jungen Orchester per E-Mailreservierung gemacht. Das hat gut geklappt. Wir möchten daher eine neue Mailadresse erstellen, über die so etwas in Zukunft passieren kann.

Bitte erstellt also die Mailadresse "karten@agv-muenchen.de"

Den Zugang zu diesem Account bekommt dann jeweils der Veranstaltungsvorganisator. Dazu reicht in meinen Augen die Weitergabe des Zugangspassworts. 

Vielen Dank!

Markus

**Comment by tmaier** [comment]
Anmeldung über Mail? Das muss ja jemand manuell pflegen...

karten@ ist sehr generisch. Das würde nicht skalieren, wenn diese Mail Adresse bei 10 Veranstaltungen verwendet wird. Erstens wer pflegt die Listen? Zweitens, werden Mails kommen wie "ich komme +1" ohne Angabe von der Veranstaltung und dem konkreten Tag 

Bitte überlegt euch eine bessere und moderne Lösung.

## Anforderungen
* kein Verwaltungsaufwand.
* ermögliche Anmeldung am Newsletter (den von Fr. Kunisch)
* qr Code und/oder Short URL agvm.net/konzert-a auf Plakat drücken. Diese ermöglicht ein Tracking und auswerten über welche Kanäle die Besucher kamen

## Lösungsmöglichkeiten

* Ganz früher hatte Klaas selbst eine php Anwendung geschrieben. Die gibt es natürlich nicht mehr.
* dann würde amiando verwendet. Schau euch das mal an.
* eine gute Lösung kann auch http://attending.io darstellen. Das habe ich kürzlich mal verwendet

Wenn ihr nach Lösungen googelt, dann sucht nach "RSVP"

**Comment by tmaier** [comment]
Btw. Eingerichtet
