### ISSUE TITLE
Kontaktdaten Homepage, bitte Fam. Clasen löschen

### ISSUE THREAD

**Issue by agv-gs** [AGVM/www.agv-muenchen.de#330]
Bitte dringend den Namen des alten Hausmeisters aus der Homepage löschen (Fam. Clasen)
und durch  "n.n". ersetzen - danke!
Wir haben ein neues Bewerbungsverfahren laufen und die Leute rufen die Hausmeisternummer an um Infos zu bekommen. Herr Dunic ist aber ab Montag nicht mehr zu erreichen. Alle Bewerbungen sollen direkt in der Geschäftsstelle auflaufen.
Danke
M. Kunisch

**Comment by Aktivitas-x** [comment]
bitte im gleichen Zug die Kontakmail der Aktivenvorstandschaft ändern.
alt: vorstandschaft@ag-muenchen.de
neu: vorstandschaft@agvm-aktivitas.de

Vielen Dank,

Markus

**Comment by tmaier** [comment]
Eure Mail-adresse, genauso wie alle x@ Mail Adressen werden doch weiter geleitet... Geht das nicht mehr oder was sind da eure Gedanken?

**Comment by Aktivitas-x** [comment]
Das geht schon, alles gut!
Bei vorstandschaft@agvm-aktivitas bekommen es aber alle Vorstandsmitglieder, bei der alten Adresse werden die Mails nicht an fm,bw,gw weitergeleitet.

**Comment by tmaier** [comment]
Aha. Das nennt man dann einen Bug. ich habe jetzt die fehlende Weiterleitung eingerichtet bei 1&1.

**Comment by tmaier** [comment]
@Aktivitas-x, bitte immer pro Thema ein ticket aufmachen. Dein Thema ist nämlich jetzt erledigt. Das Ursprüngliche aber nicht.

@mbergmann1324, kannst du da rein schauen? Danke!

**Comment by Aktivitas-x** [comment]
Jungs wie schaut hier aus? Die Änderung sollte langsam wirklich passieren!

**Comment by mbergmann1324** [comment]
Auf der Kontaktseite kann ich nichts bearbeiten. All die anderen Seiten schon, habe es jetzt bei zwei verschiedenen pc's versucht.

**Comment by mbergmann1324** [comment]
Ok, third times the charm. Linux hat es gebracht.
