### ISSUE TITLE
Startseite ändern

### ISSUE THREAD

**Issue by Aktivitas-x** [AGVM/www.agv-muenchen.de#331]
Servus Jungs,

soweit ich weiß, ist auf der HP ja "nur" die Kalenderfunktion kaputt. Oder liege ich da falsch?

Die Meldung mit den Technischen Problemen auf der Startseite vermittelt aber weitreichendere Probleme. Können wir die Meldung bitte raus nehmen und sie dafür nur an die Stelle setzen, für die sie auch relevant ist? Also zum Kalender.

Das wäre super, vielen Dank!

**Comment by AGropp** [comment]
Erledigt.
