### ISSUE TITLE
Kalender-Workaround aufbauen

### ISSUE THREAD

**Issue by tmaier** [AGVM/www.agv-muenchen.de#332]
Bitte richte einen Google Calendar ein mit allen Veranstaltungen. Alles @agvm-aktivitas.de-Mitglieder müssen den bearbeiten können

Gebe ihn dann öffentlich frei.

Nenne mir dann hier den Link zur öffentlich abrufbaren iCal-Datei (read-only)

Ich werde dann http://veranstaltungen-ical.agv-muenchen.de/ auf diese Adresse umbiegen. Das ist der Link, den man in seinem Kalender-Programm abonnieren soll.

* https://en.support.wordpress.com/google-calendar/
* https://wordpress.org/plugins/google-calendar-events/

**Comment by AGropp** [comment]
Markus, brauchst Du dazu Hilfe?

**Comment by Aktivitas-x** [comment]
Hilfe nehme ich gerne an. Ich weiß nicht genau wann ich dazu komme mich da kurz rein zu lesen, stehe kurz vor der Klausurenphase. 
Grundsätzlich aber mal super gut, dass man das umgehen kann und somit wieder eine ical-Datei zur Verfügung stellen kann!

**Comment by Aktivitas-x** [comment]
ok, ich merke gerade, einen GoogleCalender zu erstellen sollte nicht das große Problem darstellen😂

Vielleicht finde ich dazu sogar heute auf der Zugfahrt Zeit.

**Comment by AGropp** [comment]
Hey Markus, wie siehts aus?

**Comment by Aktivitas-x** [comment]
Ich komme gerade überhaupt nicht dazu. Falls jemand Bock hat, kann er mir gerne zuvor kommen. Ich könnte es bis spätestens Anfang Februar machen.

**Comment by AGropp** [comment]
Haben wir denn eine aktuelle Terminliste für das SS? Ich könnte mich dann daran setzen. Allerdings müsstest Du kurz mit der X-Adresse den Kalender erstellen und dann allen anderen Vorständen Bearbeitungsrechte geben - sowie mir persönlich. Am Besten mit meiner Adresse AlexanderSGropp@gmail.com
Ich kann ja dann die Einträge machen.

**Comment by Aktivitas-x** [comment]
Ist das noch aktuell? BG Chris

**Comment by AGropp** [comment]
https://calendar.google.com/calendar/ical/agvm-aktivitas.de_9varpu4honlrjq2kn8k4l4hsac%40group.calendar.google.com/public/basic.ics

Kalender ist nun unter diesem Link abbonnierbar
