### ISSUE TITLE
Aktualisierung Großes Orchester

### ISSUE THREAD

**Issue by AndreasHornHorn** [AGVM/www.agv-muenchen.de#333]
Betrifft: https://www.agv-muenchen.de/musik-und-theater/grosses-orchester/projekte-termine-konzerte/
Programm: altes Programm entfernen. Text ab 03.11. ... entfernen

Konzert: altes Konzert entfernen

Betrifft: https://www.agv-muenchen.de/musik-und-theater/grosses-orchester/biographie/
Bitte Folgende Veranstaltungen hinzufügen:

Konzert am 31.10.2015

Große Aula der LMU - Geschwister-Scholl-Platz 1, 80539 München
Leitung: Michael Konstantin

Konzertprogramm:
D-moll Sinfonie (C. Frank)
Tripelkonzert (L. v. Beethoven)
Masquerade (A. Khachaturian)

Konzert am 10. Juli 2015

Himmelfahrtskirche München – Sendling, Kidlerstraße 15,
81371 München
Leitung: Franz Schledorn

Konzertprogramm

Großes Orchester mit Big Band
Musik von Frank Sinata, Rat Pak, u. a.
Konzert am 07. Februar 2015

Himmelfahrtskirche München – Sendling, Kidlerstraße 15, 81371 München
Leitung: Michael Konstantin

Konzertprogramm

2. Sinfonie D.125 (F. Schubert)
„Bastien und Bastienne“ (W.A. Mozart)
Solisten: Maria Czeiler (Bastienne), Stephan Lin (Bastien), Carl Rumstadt (Colas)

**Comment by AGropp** [comment]
Erledigt.
