### ISSUE TITLE
kommende Veranstaltungen eintragen

### ISSUE THREAD

**Issue by Aktivitas-x** [AGVM/www.agv-muenchen.de#335]
Aus den Reihen der Philister kommt die Bitte, gerade auch für alte Herren die sich über die HP informieren alle Termine einfach schriftlich auf einer statischen Seite online zu stellen. Solange bis der Kalender wieder geht. Die Bitte wurde von mehreren Bundesbrüdern an ihre Vorstände herangetragen, deshalb bitte folgendes unter https://www.agv-muenchen.de/veranstaltungen/ veröffentlichen. 

Januar
Fr. 15.1 Konzert: Jg. Orchester und Blasorchester 20:00 Uhr
Sa. 16.1 Konzert: Jg. Orchester und Blasorchester 19:00 Uhr
So. 17.1 Konzert: Jg. Orchester und Blasorchester 17:00 Uhr

Sa., 23.1 Ball der Musen, 20:00 Uhr, Bayerischer Hof

Mi., 27.1 Gitarrenkonzert: Bbr. Vecchioni, 19:30 Uhr

Do., 28.1 Studentenliederabend, 20:00 Uhr

Sp., 31.1 kinderfasching, 15:00 Uhr

Februar
Mo., 01.2 Improvisationstheater mit SchlAGVertig, 19:30 Uhr

Do., 04.2 Abschlusspleo ho, 19:00 Uhr (Anessen ab 18:00 Uhr)

So. 07.2 Großes Orchester: Soiree, 17:00 Uhr

Sa., 20.2 Kammerkonzert: Cello Duo, 20:00 Uhr

Di., 23.2 Musengruppenabend, 19:00 Uhr

Sa., 27.2 AGV Big Band: Jazznight, 20:00 Uhr

März
Fr. 11.3, Sa. 12.3, So 13.3, Fr. 18.3, Sa. 19.3, So 20.3, Aufführung Großes Theater, 19:30 Uhr

Bitte wenn möglich zusätzlich eine PDF-Version des Semesterprogramms zum download bereit stellen. Geht das?

Vielen Dank :) Entschuldigt die vielen Umstände, aber die HP muss jetzt nach so langer Zeit wenigstens im Sparmodus mal wieder laufen. 

Grüße, Markus

**Comment by AGropp** [comment]
haben wir dazu auch Flyer?

**Comment by AGropp** [comment]
https://www.agv-muenchen.de/veranstaltungen/
ist das soweit dann in ordnung?

**Comment by markuswaidner** [comment]
Ja, past so! Flyer hab ich persönlich keine, gäbe es wenn dann bei den entsprechend verantwortlichen Personen

 

Von: Alexander Gropp [mailto:notifications@github.com] 
Gesendet: Freitag, 15. Januar 2016 14:05
An: AGVM/www.agv-muenchen.de <www.agv-muenchen.de@noreply.github.com>
Betreff: Re: [www.agv-muenchen.de] kommende Veranstaltungen eintragen (#335)

 

https://www.agv-muenchen.de/veranstaltungen/
ist das soweit dann in ordnung?
