### ISSUE TITLE
Mailadressen aktualsiseren

### ISSUE THREAD

**Issue by Aktivitas-x** [AGVM/www.agv-muenchen.de#336]
Servus zusammen,

bitte auf https://www.agv-muenchen.de/ueber-den-agv/vorstaende/aktivitas/

alle Mailadressen von ....@agv-meunchen.de  zu ....@agvm-aktivitas.de ändern. Vielen Dank. Langsam können wir die alten Adressen mal loswerden. :)

Grüße
Markus

**Comment by mbergmann1324** [comment]
Done, habe auch Flo und Hendrik als neue Fm eingetragen.

**Comment by Aktivitas-x** [comment]
Michi... dann aber bitte mir einem richtigen deutschen Satz und auch dem
richtigen Namen von Flaschl und Hendrik!!!

alt: Der Fuxmajor des WS 2015/16 ist Hendrick Blumenroth und Florian
Gaschel.

neu: Die Fuxmajores des WS2015/16 sind Hendrik Blumenroth und Florian
Dellinger.

Bitte so schnell wie möglich nochmal ändern, danke

------------------------------

Markus Waidner

1. Vorsitzender Aktivitas
Akademischer Gesangverein München <http://www.agv-muenchen.de/>
Ledererstraße 5
80331 München

0160/5964346
------------------------------

2016-01-27 12:37 GMT+01:00 mbergmann1324 <notifications@github.com>:

**Comment by mbergmann1324** [comment]
Done

**Comment by Aktivitas-x** [comment]
entschuldigung... aber es ist immer noch ein Fehler drin. "sind", nicht "ist"

**Comment by mbergmann1324** [comment]
fuck sorry
