### ISSUE TITLE
Info zu Aufführungen Gr Theater

### ISSUE THREAD

**Issue by Sierk** [AGVM/www.agv-muenchen.de#337]
https://www.agv-muenchen.de/musik-und-theater/grosses-theater/projekte-termine/
bitte CABARET Text raus und dafür:

Dieses Semester spielen wir »Geschichten aus dem Wienerwald« von Ödön von Horváth. 

Aufführungen sind am 11. / 12. / 13. / 18. / 19. und 20. März 2016
jeweils um 19:30 im Großen Saal der Scholastika. Der Eintritt ist wie immer frei.

»Geschichten aus dem Wienerwald« ist neben "Kasimir und Karoline" das bekannteste Theaterstück des österreichisch-ungarischen Schriftstellers Ödön von Horvath, das er Ende der 1920er Jahre zur Zeit der Weltwirtschaftskrise schrieb. Den Titel gab Horvath dem Stück in Anlehnung an den gleichnamigen Walzer von Johann Strauss und so spielt diese Musik eine maßgebliche Rolle. Aber so »anheimelnd« diese Walzerklänge auch sein mögen, im Stück selber wechseln sich tragische, traurige, zutiefst bitterböse und ebenso komische Elemente immer wieder ab. Knapp und lakonisch demaskiert Horvath das Klischee von »bürgerlicher Gemütlichkeit«, hinter deren Fassade sich Gemeinheit und Bösartigkeit abspielen.
Die Theatergruppe des AGV bringt mit »Geschichten aus dem Wienerwald« zum ersten Mal ein Stück von Ödön von Horvath auf die Bühne. Die »Sprachlosigkeit« der Figuren und die Diskrepanz zwischen dem was sie sagen und dem was sie wirklich meinen, diese spezielle Horvath-Atmosphäre ist es, die den Reiz ausmacht »Geschichten aus dem Wienerwald« auf die Bühne zu bringen.
Gisela Maria Schmitz

**Comment by AGropp** [comment]
Erledigt.
