### ISSUE TITLE
Aktualisierung Termine des Jungen Orchesters

### ISSUE THREAD

**Issue by thefele** [AGVM/www.agv-muenchen.de#338]

**Comment by thefele** [comment]
Bitte folgende Website mit dem angehängten Inhalt aktualisieren:
https://www.agv-muenchen.de/musik-und-theater/junges-orchester/projekte-termine-konzerte/

[website.docx](https://github.com/AGVM/www.agv-muenchen.de/files/123798/website.docx)

Danke!

**Comment by AGropp** [comment]
Erledigt.

**Comment by thefele** [comment]
https://www.agv-muenchen.de/musik-und-theater/junges-orchester/projekte-termine-konzerte/

Bitte noch ändern:
Terminplan Sommersemester 2016

Jeweils einen Absatz entfernen nach:
"Messa di Gloria, Giacomo Puccini"
"Samstag, 30.04.2016 um 21:45 Uhr im AGV – Bilder einer Ausstellung"
"Stiftungsfestkonzert"
"Samstag, 02.07.2016 um 19:00 Uhr im Herkulessaal – Dvořák, Puccini"
"Samstag, 09.07.2016 um 19:00 Uhr in der Dominikanerkirche in Landshut – Dvořák, Puccini"
"17.06. bis 19.06. in der Landesakademie Ochsenhausen – Stiftungsfestkonzert"

Danke!
