### ISSUE TITLE
Blasorchester Kontaktmail falsch

### ISSUE THREAD

**Issue by thefele** [AGVM/www.agv-muenchen.de#339]
https://www.agv-muenchen.de/musik-und-theater/symphonisches-blasorchester/kontakt/
bitte die gmail raus nehmen und blasorchester@agv-muenchen.de angeben

**Comment by thefele** [comment]
Der derzeitige Ansprechpartner für Interessenten ist Florian Mayer
bitte ändern...das ist absofort aus gegebenem Anlass Jakob Kobler

**Comment by AGropp** [comment]
Erledigt.
