### ISSUE TITLE
Blasorchester Foto

### ISSUE THREAD

**Issue by thefele** [AGVM/www.agv-muenchen.de#340]
https://www.agv-muenchen.de/musik-und-theater/symphonisches-blasorchester/

![imgp1498](https://cloud.githubusercontent.com/assets/3012029/12953435/bce53a60-d01a-11e5-8d29-f381d16557c7.jpg)

**Comment by AGropp** [comment]
Das Problem ist leider bekannt. Unser Informatiker Michi Lohr wird sich nach den Prüfungen um die Website kümmern. Wir werden die neuen Bilder dann einpflegen.

**Comment by thefele** [comment]
gibts da neue infos? Bzw. geht es inzwischen oder nach wie vor nicht?

**Comment by michaellohr** [comment]
Also von der technischen seite her sollte das Bilder/Content/etc einfügen nun einwandfrei funktionieren.

**Comment by thefele** [comment]
top...wäre super wenn man das Ding dann in die Öffentlichkeit entlassen könnte ;-)
https://www.agv-muenchen.de/musik-und-theater/symphonisches-blasorchester/
zwischen Überschrift und Text!

**Comment by tmaier** [comment]
@AGVM/webmasters bitte nochmal probieren.

**Comment by mbergmann1324** [comment]
Da klappt bei mir gar nichts. Ich habe auch versucht, die Fotos auf andere Websites zu speichern, dann wird das foto im Bearbeitungsmodus angezeigt, bevor es dann als normaler Nutzer stirbt.

**Comment by thefele** [comment]
hilfts wenn ich euch das ding als email schick oder in nem anderen Format?

**Comment by michaellohr** [comment]
http://agv-muenchen.de/musik-und-theater/symphonisches-blasorchester/
Erledigt.

@mbergmann1324 ging bei dir wahrschl nicht weil das Bild 6mb groß war. PhP hat da ein eingebautes upload limit. Aber man sollte generell nicht so große bilder aufgrund der Ladezeiten hochladen. Habe es dann in Photoshop runterskalliert und auf unsere homepage hochgeladen.
Dann am besten noch den Cache leeren, falls es nicht sofort angezeigt wird. (Das geht so: https://i1.someimage.com/FO0PtAv.png)
