### ISSUE TITLE
Aktualisierung Termine Blasorchester

### ISSUE THREAD

**Issue by thefele** [AGVM/www.agv-muenchen.de#341]
https://www.agv-muenchen.de/musik-und-theater/symphonisches-blasorchester/projekte-und-termine/

[homepageaktualisierung SBO.docx](https://github.com/AGVM/www.agv-muenchen.de/files/125123/homepageaktualisierung.SBO.docx)

**Comment by mbergmann1324** [comment]
Habe Sachen leicht verändert, sodass es schön ist. sag ob du glücklich bist
