### ISSUE TITLE
Konzert-Event Big Band Facebook & Homepage

### ISSUE THREAD

**Issue by Bewilderbeast** [AGVM/www.agv-muenchen.de#342]
Hi,
könntet ihr bitte die Seite:
https://www.agv-muenchen.de/musik-und-theater/big-band/projekte-termine-konzerte/
aktualisieren (Weihnachtskonzert raus, und Jazz das a spendieren) und ein Facebook-Event für das Event erstellen:

Datum: 27.02., 20:00
Titel: AGV München BigBand: Jazz Night

Text:
München bleibt München, wie es singt und lacht!

Gemäß dieses altbayerischen Mottos beginnen wir, die AGV Big Band, unser Jazz-Jahr 2016. Nach minutiöser Vorbereitung können wir Ihnen voller Stolz ein kunterbuntes Faschings-Programm präsentieren, dass die beliebtesten Klassiker vergangener Konzerte sowie AGV Big Band Neuheiten vereint. Wieder einmal wird um die Wette geschunkelt, bis die Krankenschwester kommt.

Die Band, das sind der Leiter Franz Schledorn und seine fröhlichen Musikanten (hauptsächlich blutjunge Studenten aus den verschiedensten Fachrichtungen), freut sich auf Ihre Unterstützung. Auch wenn wir nicht immer so aussehen - das Repertoire verlangt uns einiges ab und wir haben auch noch Spaß dabei.

Also tun Sie es uns gleich, zücken Sie das Partyhütchen und feiern Sie mit uns die allseits beliebte fünfte Jahreszeit. Stimmen Sie ein, wenn es wieder heißt: „Alaaf!“, „Helau!“ und „Wolle mer se rein lasse?“

Wir freuen uns auf Sie, der Eintritt ist wie immer frei!

Vielen Dank!
![img_4803](https://cloud.githubusercontent.com/assets/9408724/12971235/05c27d82-d099-11e5-8c81-12b233fd6cae.JPG)

**Comment by mbergmann1324** [comment]
Hope you're happy.

**Comment by Bewilderbeast** [comment]
Vielen Dank!
