### ISSUE TITLE
Korrektur Junges Orchester

### ISSUE THREAD

**Issue by thefele** [AGVM/www.agv-muenchen.de#344]
https://www.agv-muenchen.de/musik-und-theater/junges-orchester/projekte-termine-konzerte/

Bitte noch ändern:
Terminplan Sommersemester 2016

Jeweils einen Absatz entfernen nach:
"Messa di Gloria, Giacomo Puccini"
"Samstag, 30.04.2016 um 21:45 Uhr im AGV – Bilder einer Ausstellung"
"Stiftungsfestkonzert"
"Samstag, 02.07.2016 um 19:00 Uhr im Herkulessaal – Dvořák, Puccini"
"Samstag, 09.07.2016 um 19:00 Uhr in der Dominikanerkirche in Landshut – Dvořák, Puccini"
"17.06. bis 19.06. in der Landesakademie Ochsenhausen – Stiftungsfestkonzert"

Danke!

**Comment by mbergmann1324** [comment]
@thefele hahaha gelöst Lusche
