### ISSUE TITLE
Weiterleitung gr. Orchester E-Mailadress

### ISSUE THREAD

**Issue by cmddev** [AGVM/www.agv-muenchen.de#345]
Wir haben am vergangen Musengruppenabend eine weitere Orchestersprecherin gewählt: Christina Hagl. Könntet Ihr sie an den entsprechenden stellen bitte als Kontakt dazuschreiben und die Mails an die Orchester E-Mail-Adresse auch an ihre Adresse weiterleiten: tina.hagl@web.de

**Comment by tmaier** [comment]
@michidk: bitte entferne die Weiterleitung von der mail adresse des sprecher des gr. orchesters. Erstetze sie durch ein gemeinsames Postfach und teile Andreas Horn und Tina das Passwort und die Zugangsdaten mit. Danke

**Comment by AndreasHornHorn** [comment]
Finde ich unnötig kompliziert, da wir dann beide die Postfächer neu auf unseren Geräten einrichten müssen und wir die Kommunikation untereinander ja auch per Mail führen. Dann müssten wir uns ja Mails an uns selber schicken. Ich halte die Weiterleitung nach wie vor für sinnvoll.

**Comment by michaellohr** [comment]
Von welcher E-Mail Adresse reden wir gerade? orchester@agv-muenchen.de?

**Comment by cmddev** [comment]
Ja genau!

**Comment by michaellohr** [comment]
Ok, wie ich sehe wurde das bereits Erledigt. (an tina.hagl@web.de wird bereits weitergeleitet)
Bei http://agv-muenchen.de/musik-und-theater/grosses-orchester/kontakt/ habe ich ihren Namen hinzugefügt.
