### ISSUE TITLE
Großer Chor

### ISSUE THREAD

**Issue by thefele** [AGVM/www.agv-muenchen.de#347]
http://agv-muenchen.de/musik-und-theater/grosser-chor/projekte-termine-konzerte/
Bitte Termien aktualisieren:
Programm:
Te Deum, Antonín Dvořák
Messa di Gloria, Giacomo Puccini
Konzerte:
Stiftungsfestkonzert
Samstag, 02.07.2016 um 19:00 Uhr im Herkulessaal – Dvořák, Puccini
Samstag, 09.07.2016 um 19:00 Uhr in der Dominikanerkirche in Landshut – Dvořák, Puccini
Reguläre Proben...das passt so...
Probenwochenende
17.06. bis 19.06. in der Landesakademie Ochsenhausen – Stiftungsfestkonzert

**Comment by mbergmann1324** [comment]
Sag mir sobald du ein Probenbeginn hast, sonst fertig
