### ISSUE TITLE
Big Band Konzerte Sommer 2016 / Website

### ISSUE THREAD

**Issue by Bewilderbeast** [AGVM/www.agv-muenchen.de#348]
Hi,
wir brauchen wieder Änderungen für die Big Band-Seite:

http://agv-muenchen.de/musik-und-theater/big-band/

Die erste und letzte Zeile kann bleiben, ansonsten:

Dieses Semester spielen wir zwei Konzerte:
Das erste Konzert findet am 07.05.2016 um 20:00 Uhr im großen Saal der Scholastika statt. Die AGV Big Band wird an diesem lauen Frühlingsabend gewohnt sanfte Harfentöne erklingen lassen – falls Sie nur genau genug hinhören. Es kann aber auch sein, dass die Harfe ein wenig untergeht, wenn die 20-köpfige Band bewährte Klassiker ihres Repertoires sowie brandneue Jazz-Arrangements zum Besten gibt. Frühjahrsmüdigkeit? Fehlanzeige.

Seien Sie wieder mit dabei und genießen Sie einen entspannten und unterhaltsamen Abend mit der Big Band Ihres Vertrauens – so geht Frühling!

Das zweite Konzert ist wie jedes Semester unsere Jazz Night am 23.07..2016 um 20 Uhr ebenfalls im großen Saal der Scholastika.

Und
http://agv-muenchen.de/musik-und-theater/big-band/projekte-termine-konzerte/

Bei Konzerte:

07.05.2016, 20:00: Frühlingskonzert
23.07.2016, 20:00: Jazz Night

Falls ihr Events erstellt: Details sind in der Facebook-Event-Issue

Vielen Dank!

**Comment by AGropp** [comment]
Erledigt.
