### ISSUE TITLE
Big Band Konzerte Sommer 2016 / Facebook

### ISSUE THREAD

**Issue by Bewilderbeast** [AGVM/www.agv-muenchen.de#349]
Hi,
wir brauchen ein neues Facebook-Event für's nächste Konzert:

07.05.2016, 20:00

Titel: AGV Big Band: Frühlingskonzert

Horch, von fern ein leiser Harfenton!

Ist es nicht einfach herrlich? Blumen blühen in prächtigen Farben, Vögel zwitschern al­lent­hal­ben und Frühling lässt sein blaues Band wieder flattern durch die Lüfte. Und auch uns drängt es aus dem dunklen Kämmerlein hinaus an die frische Luft und hinauf auf die große Bühne.

Die AGV Big Band wird an diesem lauen Frühlingsabend gewohnt sanfte Harfentöne erklingen lassen – falls Sie nur genau genug hinhören. Es kann aber auch sein, dass die Harfe ein wenig untergeht, wenn die 20-köpfige Band bewährte Klassiker ihres Repertoires sowie brandneue Jazz-Arrangements zum Besten gibt. Frühjahrsmüdigkeit? Fehlanzeige.

Seien Sie wieder mit dabei und genießen Sie einen entspannten und unterhaltsamen Abend mit der Big Band Ihres Vertrauens – so geht Frühling!

Wir freuen uns auf Sie, der Eintritt ist wie immer frei!

Vielen Dank
![2016_05_07 fruhlingskonzert a6 1 0 0 seite 1](https://cloud.githubusercontent.com/assets/9408724/14570992/44d36564-0347-11e6-9500-0b9cee613135.jpg)

**Comment by AGropp** [comment]
Erledigt.

Habe auch parallel das Event auf der Homepage upgedatet und einen Promotionsartikel auf der Startseite erstellt.

**Comment by Bewilderbeast** [comment]
Vielen Dank!
