### ISSUE TITLE
Konzertankündigung Sinfonisches Blasorchester

### ISSUE THREAD

**Issue by thefele** [AGVM/www.agv-muenchen.de#351]
Servus, könntet ihr bitte eine Konzertankündigung anbringen auf der Homepage...
![plakat musicalkonzert](https://cloud.githubusercontent.com/assets/3012029/15520109/f89e69b4-2204-11e6-9838-cb412c82543c.jpg)

Danke...
und auf Facebook hab ichs auch schon geschrieben...ich bitte eine Veranstaltung zu erstellen, das dürfen wir doch nicht...nicht wahr?

**Comment by AGropp** [comment]
Servus, gibt es einen Text?

**Comment by AGropp** [comment]
Erledigt.
