### ISSUE TITLE
Änderungen Großer Chor - Abschalten FB Seite

### ISSUE THREAD

**Issue by ontellutas** [AGVM/www.agv-muenchen.de#354]
Hallo zusammen,

ich bitte euch die Facebook-Seite für den Großen Chor zu deaktivieren, da der Content nicht gepflegt wird. Wir werden in Zukunft die Hauptseite des AGV nutzen um Informationen herauszugeben. 

Vielen Dank und viele Grüße

Lukas Havla
Chorsprecher Großer Chor

**Comment by Aktivitas-x** [comment]
Hallo Lukas,

ich werde versuchen die Seite des Chors in die AGV Seite einzubinden.
Facebook bietet diese Möglichkeit an. Dann werden alle Personen, die
aktuell die Chor Seite liken von der Zusammenführung informiert. Das kann
allerding ein paar Tage dauern, da Facebook solche zusammenführungen
anscheinen händisch prüft.

Beste Grüße
Christoph

------------------------------

Christoph Dietrich

1. Vorsitzender Aktivitas
Akademischer Gesangverein München <http://www.agv-muenchen.de/>
Ledererstraße 5
80331 München

0170/6895127
------------------------------

Am 21. Juli 2016 um 10:34 schrieb ontellutas <notifications@github.com>:
