### ISSUE TITLE
Aktualiserungen Junges Orchester

### ISSUE THREAD

**Issue by Junges-Orchester** [AGVM/www.agv-muenchen.de#355]
Bitte folgende Inhalte auf der website aktualisieren! 
Vielen Dank! -Tobi

http://agv-muenchen.de/musik-und-theater/junges-orchester/

# Junges Orchester

![jungesorchester_ss16](https://cloud.githubusercontent.com/assets/21125044/17810506/d95d2ede-661d-11e6-8135-135acda856f7.jpg)

Wir sind ein Studentenorchester, das auf hohem Niveau sinfonische Werke zur Aufführung bringt. Hierzu zählen unter anderem Dvořáks 9. Sinfonie „Aus der neuen Welt“, die Symphonie Fantastique von Berlioz oder aber Bernsteins Symphonische Tänze aus der “West Side Story”. Nähere Infos zu unserem aktuellen Programm findest du [hier](http://agv-muenchen.de/musik-und-theater/junges-orchester/projekte-termine-konzerte/).

### Mitspieler gesucht!
Bist du interessiert an einem großen sinfonischen Orchester? Dann bist du hier richtig. Wir sind offen für Musikerinnen und Musiker aller Art. Wenn du bei uns mitspielen möchtest, [melde Dich bei uns](http://agv-muenchen.de/musik-und-theater/junges-orchester/kontakt/)! Eine Mitgliedschaft im AGV ist dafür nicht notwendig. Wir freuen uns auf Dich!

##########

http://agv-muenchen.de/musik-und-theater/junges-orchester/projekte-termine-konzerte/

# Projekte, Termine, Konzerte

[Termine.docx](https://github.com/AGVM/www.agv-muenchen.de/files/427097/Termine.docx)
[Tabelle bitte einbinden]

Allen, die im Orchester mitspielen möchten und sich die Probenarbeit einmal ansehen wollen, seien diese Termine eine herzliche Einladung.

##########

http://agv-muenchen.de/musik-und-theater/junges-orchester/dirigent/

# Dirigent

##########

http://agv-muenchen.de/musik-und-theater/junges-orchester/biographie/

# Biographie & Repertoire

![neujahrskonzert-1634](https://cloud.githubusercontent.com/assets/21125044/17812178/3fb8c8c0-6626-11e6-99e6-28a9b6532cc0.jpg)

Aus einem kleinen Projektorchester heraus wurde im Jahre 1998 das Junge Orchester als erweiternde Institution des AGV gegründet. 2012 übernahm Bbr. Thomas Hefele die musikalische Leitung und formt seitdem den Klangkörper in den wöchentlichen Proben maßgeblich. Das Orchester widmete sich in Folge zunehmend anspruchsvollen sinfonischen Werken, unter anderem der Sinfonie „Aus der neuen Welt“ von Antonín Dvořák, Leonard Bernsteins „Symphonic Dances“ aus der West Side Story und im vergangenen Jahr der „Symphonie Fantastique“ von Hector Berlioz.
Aktuell besteht das Junge Orchester aus rund 70 motivierten jungen Musikerinnen und Musikern – vorwiegend Studierenden –, die nicht nur als musikalisches, sondern auch als familiäres Ensemble stark zusammengewachsen sind. Abseits der konzentrierten Probenarbeit begeistern sich die Orchestermitglieder auch für gemeinsame Wochenenden auf der Drehmöser Hütte am Wetterstein oder am Segelgrundstück des AGV am Ammersee.

Unter unserem bisherigen Dirigenten Thomas Hefele wurden u. a. folgende Werke aufgeführt:

- Antonin Dvorák: Sinfonie Nr. 9 „Aus der neuen Welt“
- Antonin Dvorák: Die Mittagshexe
- Bedrich Smetana: Die Moldau
- Gioachino Rossini: Ouvertüre zu „Der Barbier von Sevilla“
- Johannes Brahms: Ungarische Tänze Nr. 1-5
- Leonard Bernstein: Symphonic Dances aus „West Side Story“
- Joseph Haydn: Sinfonie Nr. 104 „Londoner Sinfonie“
- Wolfgang Amadeus Mozart: „Eine kleine Nachtmusik“
- Franz Schubert: Sinfonie Nr. 8 „Die Unvollendete“
- Franz Schubert: Messe Es-Dur

########

http://agv-muenchen.de/musik-und-theater/junges-orchester/kontakt/

# Kontakt

### Unser Orchestersprecher-Team
Julia Wimmer, Sandro Süß, Tobias Boolakee und Johann Steinert
jungesorchester@agv-muenchen.de

### Musikalische Leitung
Christoph Schäfer
dirigent.jungesorchester@agv-muenchen.de

### Sitz und Probenort
AGV Akademischer Gesangverein München e.V.
Ledererstraße 5
80331 München

**Comment by blacktalon567** [comment]
Die Änderungen wurden nun übernommen, schau am Besten nochmal drüber, ob alles passt.

**Comment by Junges-Orchester** [comment]
Wunderbar, vielen Dank!
