### ISSUE TITLE
Dirigent Junges Orchester

### ISSUE THREAD

**Issue by Junges-Orchester** [AGVM/www.agv-muenchen.de#356]
Bitte das auch noch aktualisieren.
Vielen Dank! -Tobi

#######

http://agv-muenchen.de/musik-und-theater/junges-orchester/dirigent/

# Dirigent
### Christoph Schäfer
![foto vincent schmucker](https://cloud.githubusercontent.com/assets/21125044/18051672/5246cd20-6df6-11e6-9e0b-8273258d20c1.jpg)
[Bild bitte im Fließtext, siehe auch http://agv-muenchen.de/musik-und-theater/grosses-orchester/dirigent/]

Der gebürtige Münchner Christoph Schäfer studiert derzeit im Masterstudiengang Dirigieren/Chorleitung an der Hochschule für Musik und Theater München bei Prof. Michael Gläser.

Sein Dirigierstudium führte ihn zudem an die Universität für Musik und darstellende Kunst Wien (Prof. Erwin Ortner, Prof. Konrad Leitner) sowie die Musikhochschule Regensburg (Prof. Steven Heelein, GMD Tetsuro Ban). Parallel zum künstlerischen Studiengang "Dirigieren" absolvierte er an der Universität Regensburg das Staatsexamen Lehramt Musik für Gymnasium.

Geprägt durch sein musikalisches Elternhaus kam er bereits in jungen Jahren mit Musik verschiedenster Epochen sowie zeitgenössischen Kompositionen in Berührung, die bis heute einen festen Bestandteil seines Repertoires ausmachen.

Eine weitere zentrale Rolle wird Freiherr Enoch zu Guttenberg zu teil, der ihn seit mehreren Jahren als Mentor und musikalischen Förderer unterstützt und in seiner dirigentischen Entwicklung begleitet. Dies ermöglichte ihm in den letzten Jahren Auftritte angroßen Konzerthäusern im In- und Ausland (2016 u.a. China, Südkorea) sowie bei den Internationalen Herrenchiemsee Festspielen.

Neben der Arbeit mit diversen Orchestern (u.a. Prager Philharmoniker) und Chören (u.a. Neuer Kammerchor Regensburg) gründete er 2014 das "StimmGold Vokalensemble" mit dem er neben deutscher romantischer Chorliteratur einen Schwerpunkt auf die Aufführung kontemporärer Werke legt. Besonders bedeutsam für seine sängerische Laufbahn war die Mitwirkung im renommierten Arnold Schönberg Chor Wien sowie der Chorgemeinschaft Neubeuern. 

Seit 2016 ist Christoph Schäfer Dirigent des sinfonischen Jungen Orchesters des Akademischen Gesangvereins München.

**Comment by blacktalon567** [comment]
Hab ich nun so eingefügt, schau nochmal drüber, ob's passt.
