### ISSUE TITLE
Mitgliedsantrag auf HP verfügbar machen

### ISSUE THREAD

**Issue by Aktivitas-x** [AGVM/www.agv-muenchen.de#361]
Früher war der Mitgliedsantrag auf der Seite abrufbar.
Damit muss man nicht immer erst zur Vorstandschaft gehen, sondern kann den im Bedarfsfall selber ausdrucken.
Ich würde vorschlagen, das unter agv/verbindung/passen wir zusammen, unten einzufügen.
Schreibt mir ne kurze Nachricht, dann gibts den aktuellen als PDF

lg Kilian

**Comment by michaellohr** [comment]
Erledigt:
http://agv-muenchen.de/ueber-den-agv/die-verbindung/passen-wir-zusammen/
http://agv-muenchen.de/wp-content/uploads/2016/10/Aufnahmeantrag.pdf
