### ISSUE TITLE
Gr. Orchester FB-Page Rechte

### ISSUE THREAD

**Issue by cmddev** [AGVM/www.agv-muenchen.de#366]
Bitte die FB-Rechte zum Posten vom Gr. Orchester an folgende Persoenen vergeben:
https://www.facebook.com/raphael.mayrhofer.3
https://www.facebook.com/christina.hagl.7
https://www.facebook.com/andreashornhorn

**Comment by Aktivitas-x** [comment]
Ich kümmer mich drum.
#closed

**Comment by cmddev** [comment]
Wie lange wird das etwa dauern? Wir würden gerne nämlich schon am Wochenede von Proben-WE proben.

mit freundlichen Grüßen,
Andreas Horn

**Comment by Aktivitas-x** [comment]
bitte die freundschaftsanfrage von vorstand aktivitas annhemen.

**Comment by cmddev** [comment]
Grade gemacht! :)

mit freundlichen Grüßen,
Andreas Horn

**Comment by Aktivitas-x** [comment]
bitte christina und raphi bescheid sagen

**Comment by cmddev** [comment]
Danke, habe ich Bescheid gesagt, Christina hat wohl auch gerade angenommen.

mit freundlichen Grüßen,
Andreas Horn
