### ISSUE TITLE
Facebook Admin

### ISSUE THREAD

**Issue by Junges-Orchester** [AGVM/www.agv-muenchen.de#367]
Bitte für die "Junges Orchester des AGV" Facebook Seite "Sandro Züz" Admin Rechte geben.
Vorstand hat auf IT-Admin verwiesen, der wieder auf den Vorstand verwiesen hat. Wäre gut, wenn sich der tatsächlich Berechtigte hiermit angesprochen fühlt.

**Comment by michaellohr** [comment]
Wer ist den für die Facebook-seite zuständig?

**Comment by Aktivitas-x** [comment]
Erledigt
