### ISSUE TITLE
Facebook-Veranstaltung/Homepage-Ankündigung Bayerischer Abend

### ISSUE THREAD

**Issue by JustAnotherAccount23** [AGVM/www.agv-muenchen.de#368]
Servus, wir bräuchten ne Facebook-Veranstaltung und HP-Ankündigung 
"Bayerischer Abend des Wohnheims" 
Datum: 10.11.2016 18:00 Uhr
Ort: Philisterzimmer AGV

Text: "Musi, Fassbier und was zünftiges zum Essen – Alles was das Herz begehrt!
Es ist wieder Zeit für den traditionellen Bayerischen Abend des Wohnheims. Für Verköstigung sowie Tanzlmusi (diesmal von der Gamsgetiermusi) im Philisterzimmer der Scholastika (2. Stock) ist wie immer gesorgt.
Jeder ist herzlich willkommen und über Gäste in Tracht freuen wir uns selbstverständlich besonders!"
Flyer:
![bayrischer_abend_plakat10 11 16](https://cloud.githubusercontent.com/assets/22838647/19389427/49f87d74-9224-11e6-8054-ea7ce67fb79d.png)

Vielen Dank
Andi

**Comment by blacktalon567** [comment]
Ich hab jetzt grad nur Zeit gehabt, bei Facebook die Veranstaltung zu erstellen. Das auf der Website kann ich erst morgen machen.

**Comment by blacktalon567** [comment]
Done.
