### ISSUE TITLE
Mail-Weiterleitungen

### ISSUE THREAD

**Issue by blacktalon567** [AGVM/www.agv-muenchen.de#372]
Das hat mir Julian Stein geschickt. Ich kann das aber nicht machen. Das müssten dann Michael oder Tobias übernehmen.

Hi Hung, 

kannst Du mir bitte folgende agv-mailkonten auf die untenstehenden emailadressen freischalten/weiterleiten

chor@agv-muenchen.de für raphaela.rupert@mnet-mail.de und cbowman@anglistenchor-heidelberg.de

musenwart@agv-muenchen.de für mich j.s.muenchen@gmail.com

vielen Lieben Dank!

LG Julian

Also zusammengefasst:
chor@agv-muenchen.de --> raphaela.rupert@mnet-mail.de
chor@agv-muenchen.de --> bowman@anglistenchor-heidelberg.de

musenwart@agv-muenchen.de --> j.s.muenchen@gmail.com

**Comment by michidk** [comment]
Ist bereits genau so eingestellt.

**Comment by michaellohr** [comment]
Ist bereits genau so eingestellt.
