### ISSUE TITLE
E-Mail Weiterleitung Junges Theater

### ISSUE THREAD

**Issue by markuswaidner** [AGVM/www.agv-muenchen.de#373]
Servus,

auf Grund des Wechsels des Theatersprechers des Jungen Theaters bitte einer Mailweiterleitung von jungestheater@agv-muenchen.de nach markuswaidner@me.com einrichten. Das wäre super! Vielen lieben Dank, beste Grüße,
Markus

**Comment by michaellohr** [comment]
Done
