### ISSUE TITLE
Weiterleitung von "ball-der-musen.de" auf aktuelle Ball der Musen Veranstaltung

### ISSUE THREAD

**Issue by blacktalon567** [AGVM/www.agv-muenchen.de#375]
Weiterleitung des Links: www.ball-der-musen.de
auf die Seite: http://agv-muenchen.de/Veranstaltung/agv-ball-der-musen/

**Comment by michaellohr** [comment]
Done:
http://balldermusen.de/ leitet nach http://ball-der-musen.de/ weiter
und http://ball-der-musen.de/ nach http://agv-muenchen.de/Veranstaltung/agv-ball-der-musen/
