### ISSUE TITLE
Buchungslink für Ball der Musen mit www.ball-der-musen.de verlinken

### ISSUE THREAD

**Issue by blacktalon567** [AGVM/www.agv-muenchen.de#376]
Buchungslink für den Ball der Musen: 
https://sv.laterne.de/edetail?mpn=Events&gruppe=M&eid=14300600021

--> www.ball-der-musen.de soll auf https://sv.laterne.de/edetail?mpn=Events&gruppe=M&eid=14300600021 weiterleiten.

**Comment by michaellohr** [comment]
Done.
