### ISSUE TITLE
zweiter Konzert Termin Großes Orchester

### ISSUE THREAD

**Issue by raphael-mayrhofer** [AGVM/www.agv-muenchen.de#378]
Hallo,

könntet ihr noch den zweiten Konzerttermin 27.01.16 20:00 Großer Saal im Kalender ergänzen.
Danke :)

Liebe Grüße
Raphi

**Comment by blacktalon567** [comment]
Hi Raphi,

wann sind genau die Konzerttermine. Bis jetzt stand im Kalender: 

Sa 28.01.2017 19:00-22:00 Großer Saal

Sa 04.02.2017 19:00-22:00 Himmelfahrtskirche


kommt jetzt ein dritter Termin dazu oder wird der erste Termin um einen Tag vorverlegt (mit etwas veränderter Uhrzeit)?


Grüße

Hung

**Comment by raphael-mayrhofer** [comment]
Lieber Hung,

Es ist 27.01. 20:00 und 28.01. 19:00 beides im großen Saal. 
Ich weis nich wo der 4.2. herkommt, der ist falsch. 

Liebe Grüße und danke dir!
Raphi

Raphael Mayrhofer
_______________________
Moorbadstr. 3
85221 Dachau
0160 94767801
rjn.mayrhofer@gmail.com

**Comment by blacktalon567** [comment]
Alles klar, 

ich hab den Fehler entdeckt. Am 4.2. ist das Konzert vom Großen Chor, das muss beim Erstellen des iKalenders falsch eingetragen worden sein.

Ich hab jetzt eure beiden Termine so in den Kalender eingetragen und den 4.2. dem Großen Chor zugeordnet.

**Comment by raphael-mayrhofer** [comment]
Lieber Hung,

Leider gibts am 27.01. noch eine Veranstaltung zu viel. 20.00 Uhr ist richtig.

Könntest du ausserdem noch das Plakat integrieren?
![agv_eroica_a3_2](https://cloud.githubusercontent.com/assets/3983191/21887776/967611c8-d8c1-11e6-8972-26743a1d0d9c.jpg)
