### ISSUE TITLE
Verbreitung der yarooms Daten für alle AGVer

### ISSUE THREAD

**Issue by blacktalon567** [AGVM/www.agv-muenchen.de#386]
Sehr geehrter Webmaster,
 
zur Veröffentlichung der Yaroom-Seiten an alle AGVer sollen im internen Bereich auf der AGV-Homepage die URL zum Zugriff sowie die dafür nötigen Login-Daten veröffentlicht werden. Diese sind:
 
URL:
https://agv-muenchen.yarooms.com
 
 
Login-Daten:
E-Mail: ****
Password: ****
 
Ergänzend soll folgender Hinweis aufgenommen werden:
„
-          Bitte verändert nicht die Einstellungen des Accounts unter „My account“.
-          Es können gleichzeitig mehrere User angemeldet sein.
-          Hilfe gibt es unter https://www.yarooms.com/help.
“

**Comment by blacktalon567** [comment]
Genaueres muss noch mit der Aktivenvorstandschaft besprochen werden, z.B. wie der interne Bereich aussehen soll (passwort versehen?, wo zu finden).

**Comment by tmaier** [comment]
👎  für das posten der Daten (Passwort) hier in GitHub.

👍  für die Lösung. Sieht cool aus!

Wäre es nicht besser, wenn sich jeder Nutzer ein eigenes Konto holt? Anstatt ein gemeinsames?

Interner Bereich kann in Wordpress einfach gemacht werden. Siehe Seite der Hütte. Man kann sehr einfach ein Passwort für eine Seite vergeben.

**Comment by blacktalon567** [comment]
Also die Leute, die Musengruppen, etc. organisieren, haben schon einen separaten Zugang. 
Die Daten hier sind für alle anderen AGVer gedacht. So hab ich den Mail-Verlauf zwischen Schlux und Geschäftsstelle verstanden.

Das mit dem internen Bereich auf der Homepage kenn ich, ist echt easy. Nur müsste man eben das Passwort der Seite an alle verschicken, ob das eben so gehandhabt werden soll, kläre ich mit der Vorstandschaft.

**Comment by Aktivitas-x** [comment]
Also das habs ja schonmal. Die Zugangsdaten dazu sind auch vielen bekannt.
Es ist die Frage, ob wir den Bereich wirklich brauchen. Wenn eh dann jeder der Geschäftsstelle wegen dem Passwort schreibt, kann man auch gleich die Zugangsdaten verschicken.

**Comment by michaellohr** [comment]
Das mit dem eigenen Account finde ich bisschen unötig, wenn man eh nur Leserechte hat. Ist bestimmt sehr aufwändig für jeden AGVer einen eigenen Account zu erstellen und diese dann zu Verwalten. 

Den Beitrag würde ich editieren und das Passwort rausnehmen, sonst sind die Daten ziehmlich bald auf Google zu finden. 

Man kann ja einfach beides machen: Es in den Passwort geschützen Bereich zum nachschauen (mit einem einfachen Passwort a la "Bierjunge" das sich jeder aktive merken kann) und zusätzlich einmal in die Telegram gruppe posten.
So ein Interner bereich wäre sowieso recht praktisch... Von da aus könnte man dann auf weiteres internes Zeug wie zB die Diensteliste verlinken.

**Comment by tmaier** [comment]
SSO mit GitHub oder laterne wäre cool

**Comment by Jazkiob** [comment]
Ich würde die Geschichte gerne nochmal anstoßen.

Über den Reiter AGV -> Interna -> Yarooms findet man die Unterseite (http://agv-muenchen.de/ueber-den-agv/interna/yarooms/) noch.
Bei der Link-Liste im Interna-Bereich ist sie allerdings nicht mehr zu finden.

Könntet ihr nicht relativ schnell die Variante der Hütte und auch deren PW übernehmen? Das sollte doch jedem geläufig sein :)
Nach dieser Anmeldehürde kommt man auf die von @blacktalon567 am Anfang vorgeschlagene Seite.

Dann hätten wir eine funktionierende Minimallösung, bis wir Zeit haben, eine perfekte Lösung, siehe @tmaier , einzupflegen.

**Comment by blacktalon567** [comment]
Die Seite ist aktiv, das pw ist momentan der Nachname unseres Bundesbruders, der unsern Bundesspruch komponiert hat. Ich fand das pw von der Hütte so speziell für die Seite angelegt, kann's aber auf Wunsch auch ändern.

**Comment by Jazkiob** [comment]
Danke dir - Finde ich eine super Sache für den Moment :+1: 

Allerdings fehlt noch ein Link auf der Internaseite (http://agv-muenchen.de/ueber-den-agv/interna/) zu der Yarooms Unterseite. Bis jetzt kommt man nur über das Menü in diese Unterseite :)

**Comment by blacktalon567** [comment]
Ich hab nun einen Link zur Yarooms Seite hinzugefügt.
