### ISSUE TITLE
Update GR.Orchester

### ISSUE THREAD

**Issue by cmddev** [AGVM/www.agv-muenchen.de#406]
Change: http://agv-muenchen.de/musik-und-theater/grosses-orchester/projekte-termine-konzerte/
to:

**Projekte, Termine, Konzerte**
Terminplan Wintersemester 2016/17

**Probenbeginn**:
_Dienstag 09.Mai 17, 19:00 Uhr, Großer Saal AGV (3. Stock)_

**Reguläre Proben**:
_Dienstags, 19:00 Uhr, AGV, Großer Saal (3. Stock)_

**Programm**
_Bizet – Carmen Suite I
Bizet – Carmen Suite II
Gershwin – Rhapsody in Blue_

**Öffentliche Generalprobe**:
_05.07.2017_

**Konzert**:
_07.07.2017 (Himmelfahrtskirche Sendling)_

**Comment by blacktalon567** [comment]
Ich schätze mal, dass das "Terminplan Sommersemester 2017" heißen soll ;)
Außerdem hab ich bei Probenbeginn und Reguläre Proben die Schreibweise des Ortes vereinheitlich (Reihenfolge "Großer Saal" und "AGV").
