### ISSUE TITLE
Neuer Hüttenplan als GoogleSheet

### ISSUE THREAD

**Issue by FelixWeg** [AGVM/www.agv-muenchen.de#407]
Servus Hung, 

Betreff URL: http://agv-muenchen.de/ueber-den-agv/drehmoeser-huette/interna/

-> Bitte dort wo derzeit der aktuelle Hüttenplan unter dem Namen "Belegungsplan Hütte WS2017/18" als PDF hinterlegt ist, nachfolgende URL als "Aktueller Belegungsplan" verlinken. Diese führt zu einem GoogleSheet mit einem immerwährenden aktuellen Hüttenplan!

https://docs.google.com/spreadsheets/d/18UiH6p8azQaIzTI4P2jE9bN-4aPdF_N1aNOKnrgqVGU/edit?usp=sharing

Besten Dank und bbr. Grüße!
Felix (designierter Hüttenwart)

**Comment by tmaier** [comment]
👍🏻👍🏻👍🏻
