### ISSUE TITLE
Hüttenwart Mail-Adresse

### ISSUE THREAD

**Issue by FelixWeg** [AGVM/www.agv-muenchen.de#409]
Servus Hung, 

wie funktioniert das denn mit den AGV-Mailadressen? 
Werden die einfach weitergeleitet oder kann man die konkrete Adresse auch separat bspw. in Outlook nutzen? 
Sry für die dummen Fragen - kenne mich da nicht so aus. 

BG, Felix

**Comment by FelixWeg** [comment]
P.S.: Danke für die Express-Bearbeitung!!! :D

**Comment by blacktalon567** [comment]
Sers Felix,

normalerweise müsstest du einen Login für den E-Mail Account haben/bekommen (Übergabe mit Flo Dobler). Danach kannst du die E-Mail-Adresse benutzen wie jede andere auch. 
Da ich Outlook und Weiterleitungen von E-Mail-Adressen nicht benutze, kenne ich mich da konkret auch nicht aus.
Am Besten fragst du da bspw. bei Tobi Maier oder Michi Lohr nach.

VG,
Hung
