### ISSUE TITLE
Neuer Anmeldebogen für Dreh

### ISSUE THREAD

**Issue by FelixWeg** [AGVM/www.agv-muenchen.de#413]
Servus Hung, 

ich weiß...so langsam wird's lästig. Das ist erstmal das letzte Issue. Das nächste kommt erst in ein paar Wochen. Ich würde Dich bitte noch den Anmeldebogen im Internen Hüttenbereich zu aktualisieren. 
Vielen Dank für deine schnellen Erledigungen!!!

Titel: Anmeldebogen (Stand: Mai 2017)

[201705 Anmeldebogen_Drehmöser_Hütte.pdf](https://github.com/AGVM/www.agv-muenchen.de/files/970660/201705.Anmeldebogen_Drehmoser_Hutte.pdf)

**Comment by tmaier** [comment]
Hi Felix,

wenn du das noch optimieren willst, dann könntest du auch ein Google Formular bauen.
Dann ist der gesamte Prozess digital.

* https://www.google.com/intl/de/forms/about/
* https://support.google.com/docs/answer/87809?hl=de

**Comment by blacktalon567** [comment]
Der neue Anmeldebogen wurde hinzugefügt.
