### ISSUE TITLE
Bug Report: Reiter-Menü bleibt bei Öffnen einer Seite in neuem Tab

### ISSUE THREAD

**Issue by blacktalon567** [AGVM/www.agv-muenchen.de#420]
**Wo:** Auf jeder Seite der Homepage. Handelt von der Menü Übersicht mit den Übergeordneten Tabs.

**Was:** Wenn man über das Menü eine Seite in einem neuen Tab oder Fenster aufruft, bleibt das Drop-Down Menü bestehen bis man einmal irgendwohin mit der Maus klickt (links/rechts/Mitte). 
Das Drop-Down Menü bleibt auch bestehen, wenn man mit der Mause andere Menüpunkte hovert. Dadurch überlappt sich das neue Drop-Down Menü mit dem vorherigen, das eigentlich verschwinden sollte, nachdem man die Seite in dem neuen Tab/Fenster aufgerufen hat.

Der Bug ist in den angehängten Bildern zu sehen. Getestet wurde der Bug in Google Chrome und MS Internet Explorer.

![agv homepage bug - part1](https://cloud.githubusercontent.com/assets/20127306/26059986/f9c9457e-3983-11e7-81c0-1ee1582d5a5a.png)

![agv homepage bug - part2](https://cloud.githubusercontent.com/assets/20127306/26059992/fecf055e-3983-11e7-8fe7-a551ee25017a.png)

**Ziel:** Nach dem Öffnen einer Seite über das Menü in einem neuen Tab/Fenster soll das Drop-Down Menü verschwinden.

Gruß
Hung

**Comment by michidk** [comment]
Das liegt daran das "in einem neuen Tab öffnen" keine Funktion der Website, sondern ein "Hack" deines Browsers ist. Man könnte dies beheben, indem man einfach weiter prüft ob die Maus noch in dem Menü ist. Allerdings habe ich momentan nicht die Zeit mich in den Code von dem Design einzuarbeiten.

Allerdings werden wir das für die neue Website/neues Design beachten.

**Comment by michaellohr** [comment]
Das liegt daran das "in einem neuen Tab öffnen" keine Funktion der Website, sondern ein "Hack" deines Browsers ist. Man könnte dies beheben, indem man einfach weiter prüft ob die Maus noch in dem Menü ist. Allerdings habe ich momentan nicht die Zeit mich in den Code von dem Design einzuarbeiten.

Allerdings werden wir das für die neue Website/neues Design beachten.
