### ISSUE TITLE
Gr Theater 

### ISSUE THREAD

**Issue by Sierk** [AGVM/www.agv-muenchen.de#422]
http://agv-muenchen.de/musik-und-theater/grosses-theater/biographie/
bitte die Verlinkung zum " Kirschgarten" einfügen:
https://youtu.be/xqDqMEzZAaQ

danke!

**Comment by blacktalon567** [comment]
Ich hab den Link hinzugefügt, aber aus einem mir unbekannten Grund wird kein Video auf der Seite abgespielt. Dabei wird in Wordpress selbst das Video ganz normal in die Seite eingebunden und ich kann es abspielen.

**Comment by michaellohr** [comment]
Erledigt.
