### ISSUE TITLE
Hüttenmail unter Kontakt

### ISSUE THREAD

**Issue by FelixWeg** [AGVM/www.agv-muenchen.de#426]
Servus Hung, 

ich bekomme auf die Hüttenmailadresse eine große Menge an Junkmails.

Könntest Du bitte die Adresse im Bereich "Kontakt" so bearbeiten, dass Sie von Robotern nicht mehr erkannt werden kann? Bspw. (a)

Besten Dank, Felix

**Comment by michaellohr** [comment]
Servus,
ich würds lassen. So kann man dir mit einem Mausklick ne email schreiben. Für Bots wird die email nur durch ein (a) nicht weniger lesbarer (früher wars so). Wir haben bereits eine art Add-on aktiviert, das es für bots schwieriger macht die email zu lesen/entschlüsseln. Nur der Nutzer (zum beispiel du) bekommt davon nichts mit.

**Comment by tmaier** [comment]
Ich stimme Michi zu. Bitte bei deinem Postfach den spamfilter aktivieren. Das geht für den admin über 1&1.
